### ISSUE TITLE
Installing some pkgs via init produces an error

### ISSUE THREAD

**Issue by steckerhalter** [quelpa/quelpa#1]
So running this command works in a running Emacs:

``` lisp
  (quelpa '(magit-filenotify :fetcher github :repo "magit/magit-filenotify"))
```

But having the same command in the init file produces:

```
Parsing tar file...done
error in process filter: package-buffer-info: Package lacks a "Version" or "Package-Version" header
error in process filter: Package lacks a "Version" or "Package-Version" header
```

weird that it is saying "parsing a tar file" because it's just an .el:

magit-filenotify-20131018.1155.el

I assume the webserver delivers the wrong content type.

**Comment by TheBB** [comment]
Hi @steckerhalter, we're having some problems at https://github.com/syl20bnr/spacemacs/issues/2688 with a similar symptom, but maybe a different cause. Have you seen anything like this?
