### ISSUE TITLE
CI failure due to new package-build location

### ISSUE THREAD

**Issue by vyp** [quelpa/quelpa#109]
I thought that https://github.com/quelpa/quelpa/commit/ef4f25cbb8e16039c9ba5075019a6bff7a7a17a3 was all that was needed to update for the new package-build location. But `quelpa-melpa-recipe-stores` defaults to `/recipes` from the package-build build directory, so this means that the CI will be failing. I'm not sure exactly how we want to resolve this, could be done in multiple ways.

Unfortunately I don't have time now to think about this, but because this is urgent (I think all CI builds will keep failing due to this), I will try to make time either tonight or hopefully tomorrow. Of course, feel free to suggest or resolve the issue yourselves!

**Comment by steckerhalter** [comment]
Hmm, the build seems to fail because `package-build` does not contains `recipes` anymore but is a separate repo now.

**Comment by steckerhalter** [comment]
We need to have melpa cloned into a separate location. And the recipes need to be fetched from that location.

**Comment by vyp** [comment]
For reference, here's the failing build which I forgot to link: https://travis-ci.org/quelpa/quelpa/builds/151976622

**Comment by wasamasa** [comment]
Does this change mean one must no longer install package-build from MELPA in the bootstrap script?  If yes, that would be nice, newer Emacsen even offer a `M-x install-package-from-buffer`...

**Comment by vyp** [comment]
Yes I've been thinking about the bootstrapping process too due to all the recent melpa issues. Although correct me if I'm wrong but I don't think it changes anything? IIRC the reason melpa is used for bootstrapping is in case package-build takes on a new dependency in the future, so a reliable way to ensure that package-build gets installed properly (including all potential new dependencies) is to simply install it from melpa.

For the moment I myself simply use [`load-file`](https://github.com/vyp/ui/blob/833dfd3fc0f88951395a2d1339b8ccdc2056fcd4/emacs/.emacs.d/init.el#L142-L157) to bootstrap because package-build doesn't require any non-built-in dependencies. And because I use git to lock down the version, it's guaranteed to work.

So perhaps quelpa could always use a version of package-build known not to require any other dependencies just for bootstrapping? Although that version of package-build has to be specified somewhere, and this specification has to be updated (manually) everytime package-build gets an update (that doesn't require further dependencies), so maybe this is too ugly. That being said, package-build doesn't seem to get too many updates these days so perhaps it would be permissible.

Any thoughts? Ref #76.
