### ISSUE TITLE
Interactive quelpa fails to find melpa recipie dir

### ISSUE THREAD

**Issue by Purring** [quelpa/quelpa#114]
Hey guys, today I did a clean reinstall all of my packages since the big melpa change came out.
It installs everything just fine when it's first ran, but after it's done installing all the packages in my init.el, calling `M-x quelpa`  gives me:
 ` quelpa-interactive-candidate: Opening directory: No such file or directory,  /home/cody/.emacs.d/quelpa/build/package-build/recipes`
I double checked the `quelpa-melpa-recipe-store` `quelpa-melpa-dir` and `quelpa-melpa-repo-url` are all updated to the new locations like they're supposed to, so that isn't the issue (i think).

I tried changing `package-build-recipies-dir` to the new melpa location but that didn't work, so I have no idea why package-build is looking into the wrong directory.

**Comment by steckerhalter** [comment]
you are right, it's a bug. didn't notice this was hard-coded in `quelpa-interactive-candidate`. i will push a fix
