### ISSUE TITLE
M-x package install quelpa gives "Package ‘emacs-24.3’ is unavailable"

### ISSUE THREAD

**Issue by alform** [quelpa/quelpa#117]
I found out while experimenting with spacemacs - I filed a bug with their maintainers, see https://github.com/syl20bnr/spacemacs/issues/7279

However, the issue is also present in a vanilla emacs 25.1.1, so  it should not be spacemacs dependent.

**Comment by vyp** [comment]
I cannot reproduce with emacs 25.1.1 and `~/.emacs.d/init.el` of:

``` elisp
(require 'package)
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/") t)
(package-initialize)
```

I did `M-x package-install` `quelpa` and quelpa installed and it works.

**Comment by vyp** [comment]
Also `--insecure` as used in `emacs --insecure` from https://github.com/syl20bnr/spacemacs/issues/7279 is an unknown option.

**Comment by steckerhalter** [comment]
we have this in the header of `quelpa.el`:

```cl
;; Package-Requires: ((package-build "0") (emacs "24.3"))
```

Which means install-package should make sure we have at least Emacs v24.3 but in your case it seems to try to install Emacs as a package?

**Comment by vyp** [comment]
@steckerhalter Yes that seems to be what's happening.

**Comment by steckerhalter** [comment]
it's common to do this, see for example: https://github.com/magit/magit/blob/master/lisp/magit.el#L19
@alform can you try to `package-install` magit for example?

**Comment by alform** [comment]
I found and removed some historical, unpackaged cruft lying around in /usr/share/emacs/site-lisp and that fixed it. I'm closing the issue - thanks to all who helped.

**Comment by steckerhalter** [comment]
@alform you're welcome... have a nice day
