### ISSUE TITLE
Windows php-extras in spacemacs by quelpa

### ISSUE THREAD

**Issue by GiacomoSilli** [quelpa/quelpa#118]
Hello,

I'm on Windows 10, installing spacemacs, got some errors about php
I also tried using spacemacs-develop, but I'm not able to solve the problem.

`An error occurred while installing php-extras (error: (wrong-type-argument stringp nil))`

Git is installed and in PATH.
Also accessible by spacemacs.
http://imgur.com/a/1Btam

From emacs --debug-init
http://pastebin.com/i47fsvqt

Any idea?

**Comment by wasamasa** [comment]
Judging from the backtrace and the package-build.el sources, the problem is that you don't have a GNU tar in your PATH.  Can you confirm whether installing it fixes the problem?

**Comment by GiacomoSilli** [comment]
Following this https://github.com/quelpa/quelpa#tar

Solved by changing sys PATH from C:\cygwin64\bin to C:\Program Files\emacs\bin

**Comment by CMCDragonkai** [comment]
Can it be made to work with GNU tar for windows from: http://gnuwin32.sourceforge.net/packages/gtar.htm ?

**Comment by wasamasa** [comment]
Try It And See™ (don't forget reporting back!).

**Comment by CMCDragonkai** [comment]
It doesn't work. I have it installed on PATH. CMD can find tar, Powershell can find tar. I even copied tar to emacs/bin directory (even though I use emacs64bit), and still didn't work.

**Comment by wasamasa** [comment]
Quelpa itself isn't doing anything special with tar, `package-build.el` is: https://github.com/melpa/package-build/blob/master/package-build.el#L103-L109

**Comment by steckerhalter** [comment]
@CMCDragonkai see here: https://github.com/melpa/package-build/blob/master/package-build.el#L732

in your case `package-build-tar-executable` is nil so Emacs couldn't find any tar command with:

```cl
(or (executable-find "gtar")
(executable-find "tar"))
```

You need to make this work (code from package.el):

```
defcustom package-build-tar-executable
  (or (executable-find "gtar")
      (executable-find "tar"))
  "Path to a (preferably GNU) tar command.
Certain package names (e.g. \"@\") may not work properly with a BSD tar."
  :group 'package-build
:type '(file :must-match t))
```

**Comment by CMCDragonkai** [comment]
So how is it looking up `tar`? Because I have in the Window SYSTEM PATH and both CMD and Powershell can find it.

**Comment by steckerhalter** [comment]
```cl
(defun executable-find (command)
  "Search for COMMAND in `exec-path' and return the absolute file name.
Return nil if COMMAND is not found anywhere in `exec-path'."
  ;; Use 1 rather than file-executable-p to better match the behavior of
  ;; call-process.
  (locate-file command exec-path exec-suffixes 1))
```

I guess you could set the path directly:

```cl
(setq package-build-tar-executable "/path/to/tar")
```

**Comment by CMCDragonkai** [comment]
Even after doing this:

```
  (setq package-build-tar-executable "C:/Program Files (x86)/GnuWin32/bin/tar.exe")
```

It still doesn't work, and gives me:

```
(Spacemacs) --> installing package: php-extras@php... [1/1]
Fetcher: github
Source: arnested/php-extras

Updating c:/Users/CMCDragonkai/.emacs.d/.cache/quelpa/build/php-extras/
c:/Users/CMCDragonkai/.emacs.d/.cache/quelpa/build/php-extras/php-extras-gen-eldoc.el -> c:/Users/CMCDRA~1/AppData/Local/Temp/php-extras11180x6s/php-extras-20160519.116/php-extras-gen-eldoc.el
c:/Users/CMCDragonkai/.emacs.d/.cache/quelpa/build/php-extras/php-extras.el -> c:/Users/CMCDRA~1/AppData/Local/Temp/php-extras11180x6s/php-extras-20160519.116/php-extras.el
c:/Users/CMCDragonkai/.emacs.d/.cache/quelpa/build/php-extras/dir -> c:/Users/CMCDRA~1/AppData/Local/Temp/php-extras11180x6s/php-extras-20160519.116/dir
Wrote c:/Users/CMCDragonkai/.emacs.d/.cache/quelpa/packages/php-extras-readme.txt
Error getting PACKAGE-DESC: (file-error Opening input file No such file or directory c:/Users/CMCDragonkai/.emacs.d/.cache/quelpa/packages/php-extras-20160519.116.tar)
Loading c:/Users/CMCDragonkai/.emacs.d/layers/+distributions/spacemacs-base/keybindings.el (source)...done
Done.
```

**Comment by steckerhalter** [comment]
Ok, looks like this is now a new/other problem. Can you find out why the `tar` is not there? You might want to use [Edebug](https://www.gnu.org/software/emacs/manual/html_node/elisp/Instrumenting.html#Instrumenting) for that.

Another option on Windows would be to use Emacs via Cygwin: https://github.com/quelpa/quelpa#cygwin

Native Windows support is pretty bad in general from Emacs. When I was using Windows at work a few years ago I would usually go the Cygwin route.
