### ISSUE TITLE
Error using Quelpa to install a single git hosted package with dependencies on MELPA

### ISSUE THREAD

**Issue by cowboyd** [quelpa/quelpa#119]
I'm trying to host our company's shared configuration as a single elisp package on github using quelpa so that it can be distributed easily. However, it has a lot of dependencies on packages that I _don't_ want to pull from source control. To accomplish this, I set up a bootstrap `init.el` that looks like this:

```elisp
(require 'package)

;; Add the Melpa repository to the list of package sources
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/") t)

;; Initialise the package system.
;; see https://github.com/quelpa/quelpa#installation
(package-initialize)
(if (require 'quelpa nil t)
    (quelpa-self-upgrade)
  (with-temp-buffer
    (url-insert-file-contents "https://raw.github.com/quelpa/quelpa/master/bootstrap.el")
    (eval-buffer)))

;; we only want to use frontmacs itself from sourcecontrol. 
;; Other packages should be installed from the network
;; see https://github.com/quelpa/quelpa#additional-options
(setq quelpa-checkout-melpa-p nil)

;; If the FRONTMACS_LOCAL environment is set, build the package from the local file system.
;; otherwise, pull it from the latest on github.
(if (getenv "FRONTMACS_RUNLOCAL")
    (quelpa '(frontmacs :fetcher file :path "~/../lib" ))
  (quelpa '(frontmacs :fetcher github :repo "thefrontside/frontmacs" )))

(require 'frontmacs)
```

The package itself looks like this (for now)

```elisp
;;; frontmacs.el --- Frontside config package for emacs

;; Author: Frontside  <admin@frontside.io>
;; Version: 0.1.0
;; Maintainer: Frontside <admin@frontside.io>
;; Keywords: emacs
;; Package-Requires: ((smart-mode-line))
;;
;;; Commentary:

;;; Code:

(message "Hello World")

(provide 'frontmacs)
;;; frontmacs.el ends here

```

The key thing here is that there is a dependency on `smart-mode-line`.

When I boot up emacs using this config I get the following error:

```
Debugger entered--Lisp error: (file-error "Opening directory" "No such file or directory" "/Users/cowboyd/Code/Frontside/frontmacs/build/home/.emacs.d/quelpa/melpa/recipes")
  directory-files("/Users/cowboyd/Code/Frontside/frontmacs/build/home/.emacs.d/quelpa/melpa/recipes" nil "^[^.]+")
  quelpa-get-melpa-recipe(smart-mode-line)
  quelpa-arg-rcp(smart-mode-line)
  quelpa-package-install(smart-mode-line)
  #[(req) "^H@\301\232?\205\f^@\302^H@!\207" [req emacs quelpa-package-install] 2]((smart-mode-line (0)))
  mapc(#[(req) "^H@\301\232?\205\f^@\302^H@!\207" [req emacs quelpa-package-install] 2] ((smart-mode-line (0))))
  quelpa-package-install((frontmacs :fetcher file :path "~/../lib"))
  quelpa((frontmacs :fetcher file :path "~/../lib"))
  (if (getenv "FRONTMACS_RUNLOCAL") (quelpa (quote (frontmacs :fetcher file :path "~/../lib"))) (quelpa (quote (frontmacs :fetcher github :repo "thefrontside/frontmacs"))))
  eval-buffer(#<buffer  *load*> nil "/Users/cowboyd/Code/Frontside/frontmacs/build/home/.emacs.d/init.el" nil t)  ; Reading at buffer position 843
  load-with-code-conversion("/Users/cowboyd/Code/Frontside/frontmacs/build/home/.emacs.d/init.el" "/Users/cowboyd/Code/Frontside/frontmacs/build/home/.emacs.d/init.el" t t)
  load("/Users/cowboyd/Code/Frontside/frontmacs/build/home/.emacs.d/init" t t)
  #[0 "^H\205\266^@     \306=\203^Q^@\307^H\310Q\202?^@ \311=\204^^^@\307^H\312Q\202?^@\313\307\314\315#\203*^@\316\202?^@\313\307\314\317#\203>^@\320\321\322!D\nB^R\323\202?^@\316\324^S\325^A\324\211#\210^K\324=\203e^@\326\327\330\307^H\331Q!\"\325^A\324\211#\210^K\324=\203d^@^A^S\210^K\203\247^@\332^K!\333\232\203\247^@\334^K!\211\335P\336^A!\203\201^@\211\20$
  command-line()
  normal-top-level()
```

It seems as though it is expecting `smart-mode-line` to be on the file system, but since I set the melpa checkout to false, it isn't.

**Comment by steckerhalter** [comment]
It is trying to get the recipe for `smart-mode-line` from the melpa dir. I think the easiest solution would be to install that before `frontmacs` with `(quelpa '(smart-mode-line :repo "Malabarba/smart-mode-line" :fetcher github))`

**Comment by steckerhalter** [comment]
It is also possible to define custom recipes like described here: https://github.com/quelpa/quelpa#modify-melpa-recipes

**Comment by cowboyd** [comment]
Since this is, in effect, a starter-kit for an entire company, there are plans to depend on upwards of 25 packages, not just `smart-mode-line`.  I'd prefer to just install all of them from the package archive and not from source control, which is what I thought that the `quelpa-checkout-melpa-p` variable was about.

**Comment by cowboyd** [comment]
In effect, I want *only* the `frontmacs` package to be built and installed by quelpa. Is this possible?

**Comment by steckerhalter** [comment]
Setting `quelpa-checkout-melpa-p` to `nil` will prevent the melpa repo from being cloned which contains the recipes for packages. So when `smart-line-mode` is required but not already installed it will try to find out how to get it.

So if you want to install them from the package archive you would have to do that before invoking quelpa.

**Comment by cowboyd** [comment]
It seems like there is a chicken and the egg problem, because the reason they are installed is because they are dependencies of the package that is controlled by quelpa. Having to explicitly enumerate them in the `init.el` would defeat the purpose.

Here is the use-case if it sheds any light: 

Let's say I want to add the `crux` package to our shared configuration. What I would like to do is add `crux` as a _package dependency_ of frontmacs, and then everybody just gets that new dependency when they restart emacs instead of having to change their `init.el`

Otherwise, we're no better off than just having our `init.el` in a shared git repo.

**Comment by steckerhalter** [comment]
Hmm, well `quelpa` was made to install packages amd dependencies from source code (either remote or local). In your case it might be much easier to just get `frontemacs` onto MELPA as described here: https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md

**Comment by cowboyd** [comment]
Unfortunately, I've already explored this option and it does not appear that MELPA is accepting any new packages for shared configuration. /cc @purcell

I understand that this use-case might be outside of the norm, but how hard to you see making these changes to be? If doable, I could take a stab at it.

**Comment by wasamasa** [comment]
I'd attempt writing a helper function that returns the dependencies of a package, then loop over that list and install every package not already installed via package.el.

**Comment by steckerhalter** [comment]
@cowboyd You'd have to change this function: https://github.com/quelpa/quelpa/blob/master/quelpa.el#L562 so when the dependencies are looped over it would use `package-install`. So there could be a bool setting like `quelpa-deps-from-package-archive-p` and if that is `t` it would use `package-install`?

**Comment by cowboyd** [comment]
That sounds good. Is there a way to tell if there is a quelpa configuration for a package, so that if `quelpa-deps-from-package-archive-p` is true _and_ this is not already specified to be installed from quelpa, then it would use `package-install`? Or is that overthinking it?

**Comment by steckerhalter** [comment]
No, I think it's good to think about it a bit first. How about this:

`quelpa-package-install` is modified so that it will first check if a recipe is available. So when I would call:

```cl
(quelpa 'smart-mode-line)
```

Quelpa would ask: is a recipe available for that?

1. Yes: the recipe is used to install from source code, now if there are dependencies it would ask the same question for every dependency
2. No: Fallback to `package-install` (which then automatically deps as well for that package)

Maybe the bool could be `quelpa-package-archive-fallback-p`. So quelpa would be used only if there is a recipe found or specified directly. If quelpa doesn't find a recipe it should print a warning for the user so he at least knows that there is no recipe for the given package and proceed trying to install that from the package-archive.

**Comment by cowboyd** [comment]
This sounds reasonable. I can see in the future being able to tweak the priority on a per-package basis and also to switch it around and say, try for the package archive 

>If quelpa doesn't find a recipe it should print a warning for the user so he at least knows that there is no recipe for the given package and proceed trying to install that from the package-archive.

Since this is our expected "happy-path" at least for this package, I'd prefer for there to be a way that didn't involve generating lots of warnings.

**Comment by steckerhalter** [comment]
I just thought it would be good for the user to know if some package is being installed via the package archive, but you can do it as you like...

**Comment by steckerhalter** [comment]
> now if there are dependencies it would ask the same question for every dependency

btw, since it is a recursive function it really wouldn't even have to know if it is a dependency or not

**Comment by steckerhalter** [comment]
@cowboyd can we close this issue?

**Comment by cowboyd** [comment]
I think so 👍

**Comment by steckerhalter** [comment]
thanks 🎉
