### ISSUE TITLE
Error on mac: "an error occurred while installing php-extras ..."

### ISSUE THREAD

**Issue by cjgratacos** [quelpa/quelpa#122]
Hi, I got the following error, while using emacs and installing a quelpa package, on my mac : "an error occurred while installing php-extras (error: (wrong-type-argument ...". 

I was able to fix it with homebrew by installing the gnu-tar package.

Just wanted to share the information so the Readme gets updated.

**Comment by wasamasa** [comment]
Thanks for the bug report!  I've created a PR fixing the README and am awaiting review before it gets merged.

**Comment by hlissner** [comment]
@cjgratacos @wasamasa Sorry to bring up an old issue, but I couldn't think of a better place to ask:

Looking into quelpa, package.el and tar-mode, it seems like Emacs does its own tarball I/O in-house. `tar-mode` parses the tar's literal contents into a tar-header struct, from which point files can be extracted, all (seemingly) without leaving the elisp layer.

At what point is the system tar used [such that installing gnu-tar would fix it]? Or is tar-mode a recent addition to Emacs (I'm using 25.2)?

**Comment by wasamasa** [comment]
@hlissner You're forgetting about `package-build.el`, it doesn't make use of `tar-mode`.

**Comment by hlissner** [comment]
Ah ha! There's the missing link. Thank you!
