### ISSUE TITLE
quelpa-upgrade: should not self-upgrade quelpa from Git when quelpa was installed from MELPA

### ISSUE THREAD

**Issue by ackalker** [quelpa/quelpa#126]
My setup:

- Emacs 25.1.1 on Void Linux x86_64
- quelpa installed from MELPA (using `use-package`)
- one package (`company-shell`, which I'm currently working on) cloned from Github to a local Git repository (installed using `quelpa-use-package`)

When I do `M-x quelpa-upgrade`, quelpa upgrades itself from Git, then proceeds to proceeds to upgrade my `company-shell` from my local Git repository.

From `quelpa-upgrade`'s documentation, I understand that `quelpa-upgrade` should (only) upgrade packages which are in `quelpa-cache`, not do a self-upgrade from Git as well.

I believe the problem to be with [this line](https://github.com/quelpa/quelpa/blob/d68a45fe0c4a1d4125b98adbeab65e3c8a30e908/quelpa.el#L619).
Please consider making this self-upgrade from Git optional, controlled by a variable with boolean value, similar to `quelpa-update-melpa-p`.

**Comment by steckerhalter** [comment]
added option `quelpa-self-upgrade-p` to control this: https://github.com/quelpa/quelpa/blob/master/README.md#upgrading-all-packages

**Comment by ackalker** [comment]
Thank you so much!
