### ISSUE TITLE
Autoload quelpa-checkout-melpa-p

### ISSUE THREAD

**Issue by joewreschnig** [quelpa/quelpa#130]
Aiming for zero warnings in my Emacs configuration, Quelpa is giving me some trouble. I have to set `quelpa-checkout-melpa-p` to `nil` _before_ loading the package:
```elisp
(use-package quelpa
  :init (setq quelpa-checkout-melpa-p nil))
```

But of course, it is not defined before loading the package:
```
In toplevel form:
init.el:291:35:Warning: assignment to free variable ‘quelpa-checkout-melpa-p’
```

This could be avoided by marking it with an autoload cookie. I know autoloading `defvar`/`defcustom` is considered an antipattern by some developers, but it's also rare for a package to perform heavy network-involving operations immediately upon loading.

**Comment by wasamasa** [comment]
Aiming for zero warnings in your Emacs configuration is a rather weird goal.  The existing checkers for elisp are intended for package development.  What's considered best practice there (like, not depending on yet undefined symbols) makes less sense in your init file.  I'd therefore not use one on your init file and ignore this warning.

**Comment by joewreschnig** [comment]
I agree that many elisp best-practice checks are targeted at package development, but this one is useful in all code. `(setq quelpa-melpa-checkout-p nil)` is just as wrong in an init file as it would be in a package. Quelpa's eager loading is the odd thing out here, not the warning.

**Comment by wasamasa** [comment]
What eager loading?  The package itself does nothing, that's the self-upgrading code you put in your init file.

**Comment by joewreschnig** [comment]
I referring to the eager loading of the MELPA archive by Quelpa, and was basing that on the documentation, which says

> You can disable these updates by setting quelpa-update-melpa-p to nil before requiring quelpa:

However, now checking the code, the documentation seems to be wrong. You can set `quelpa-update-melpa-p` and `quelpa-checkout-melpa-p` after `(require 'quelpa)`, as long as it's before calling `(quelpa ...)`.
