### ISSUE TITLE
Please fix the litte BUG while creating time-stamp

### ISSUE THREAD

**Issue by 2mc** [quelpa/quelpa#132]
`package-build` will fail, if there is a ZERO after the period in a time-stamp. 
Therefore your fun `quelpa-check-hash` in `quelpa.el` tries to filter that ZERO out of the time-stamp string.

However, your regexp only captures a single ZERO of possibly more then one in the time-string (i.e. when working shortly after midnight ;-).

So, please change the regexp as below:

    -          (replace-regexp-in-string "\\.0" "." (format-time-string "%Y%m%d.%H%M%S")))
    +          (replace-regexp-in-string "\\..0" "." (format-time-string "%Y%m%d.%H%M%S")))

**Comment by wasamasa** [comment]
The fix doesn't seem correct either. `\\..0` might match `.10` and replacing that with `.` is just wrong.  What you're probably after is `\\.0+`.

**Comment by 2mc** [comment]
Yes, true, one ZERO or more. Let's try it this way.

**Comment by steckerhalter** [comment]
It's pretty clear... you **shouldn't be working** shortly after midnight 😄

**Comment by 2mc** [comment]
Also true, probably (sigh).

Yet, by confirmation of the current hour, `\\.0+` works.

Let's a apply it—quickly—before it get's once more to late :rabbit:.

**Comment by SteveJobzniak** [comment]
This was discovered by @marienz. Thanks a lot for fixing it @wasamasa!

https://github.com/syl20bnr/spacemacs/issues/8901#issuecomment-304492105
