### ISSUE TITLE
How to pin packages to a specific commit/version?

### ISSUE THREAD

**Issue by ibraimgm** [quelpa/quelpa#133]
What is the correct way to "pin" packages to a specific version?

I'm currently using:
`(quelpa '(some-package :repo "foo/some-package" :fetcher github :commit "<sha-1-or-tag>"))`

I works, but I have a feeling that rewriting the entire recipe might not be a good idea.
Is there a better way?

**Comment by wasamasa** [comment]
This is how I do it.  Considering how rare changes in a recipe are, it's an acceptable trade-off.

**Comment by steckerhalter** [comment]
Yes, I would say so too. I personally always use the full recipes, even if there are no modifications necessary. When I add a new package the first time I use `quelpa-expand-recipe` to get that.

**Comment by ibraimgm** [comment]
Yep, this makes sense. I didn't knew about `quelpa-expand-recipe`, this certainly help.
Thanks for the timely response guys!

**Comment by steckerhalter** [comment]
You're welcome. Have a nice day.
