### ISSUE TITLE
`quelpa-upgrade` does not upgrade dependencies.

### ISSUE THREAD

**Issue by jaccarmac** [quelpa/quelpa#136]
This causes problems with packages such as `magit`, which will break if it gets sufficiently out of sync with `magit-popup`, a package from the same repository. Am I missing something or are dependencies not inserted into the cache?

For this usecase would it be useful to implement a command to upgrade all packages in the cache *and* their dependencies?

**Comment by steckerhalter** [comment]
No, dependencies are not inserted. Dependencies should be updated if they are required. From `magit.el`:

```cl
;; Package-Requires: ((emacs "24.4") (async "20170823") (dash "20170810") (with-editor "20170817") (git-commit "20170823") (magit-popup "20170824"))
```

So if magit-popup is not the version specified in the package it should be upgraded.

**Comment by jaccarmac** [comment]
Perhaps the problems I experienced were due to another package pinning a different version of `magit-popup`. In the case that two packages require two different versions of a dependent package, which one "wins" as far as Quelpa is concerned?

**Comment by steckerhalter** [comment]
if the required package version is higher than what is installed it should install the new version

**Comment by steckerhalter** [comment]
`Package-Requires` only sets a minimum version so in the end the highest version should prevail and both packages should be happy. I don't know what actually happens when one version is "pinned" via other means and if this even works.

**Comment by jaccarmac** [comment]
I'll have to investigate the specific interaction between `magit`, `magit-popup`, and `docker` further. Thanks for your help!
