### ISSUE TITLE
Bootstrap installed quelpa is lacking important features from latest

### ISSUE THREAD

**Issue by Purring** [quelpa/quelpa#142]
So on a completely fresh install of my config, the bootstrapped version of quelpa (0.0.1 in `list-packages`) has trouble building Magit because it depends on the package GHub, which has a dependency on let-alist that's on GNU Elpa.

Installing quelpa, upgrading it, and deleting the old version, and restarting emacs doesn't have this issue.

Seems like old versions of Quelpa that are getting bootstrapped are unable to handle fetching dependencies from gnu elpa. Is this a problem with the boostraping script, or am I just doing things the completely wrong way?

**Comment by steckerhalter** [comment]
I think it has nothing to do with the bootstrap version. The bootstrap version number defaults to 0.0.1 although it's actually the current version that is installed.

AFAIK quelpa does not fall back to gnu elpa etc. for packages so it should fail when let-alist is not available and not install it from elpa. I've added a CI test to make sure: https://github.com/quelpa/quelpa/blob/master/ci/.emacs#L7

To solve the let-alist problem I use this:

```cl
(add-to-list 'quelpa-melpa-recipe-stores
             '((let-alist :fetcher url
                          :url "http://git.savannah.gnu.org/cgit/emacs.git/plain/lisp/emacs-lisp/let-alist.el"
:version original)))
```

It adds the recipe so quelpa is able to find and install let-alist when ghub demands it. But let's see what the CI does...

**Comment by steckerhalter** [comment]
you see it fails here: https://travis-ci.org/quelpa/quelpa/jobs/357726081#L1372

I assume it works for you the second time because some other package installs let-alist?

You either have to install let-alist from elpa first or use the snippet above to install it with quelpa on-the-go.

**Comment by Purring** [comment]
Yeah, those snippets work, and getting let-alist from gnu elpa works too. This should all be fixed in the next version of emacs though, since it'll bundle the new let-alist which seems to have long times before new versions.

 It just feels dirty because [git repo linked on the GNU ELPA page](https://git.savannah.gnu.org/cgit/emacs/elpa.git/tree/packages/let-alist) is empty so i'd have to grab it out of the git tree that you linked and the version may not be the one that's correct in the future. 

Oh well, i'll cross that bridge when I get to it. Thanks for the help!

**Comment by steckerhalter** [comment]
@Purring you're welcome. I think let-alist was bundled with for emacs a while and then they moved it to elpa. I couldn't figure out what's wrong initially.
