### ISSUE TITLE
package-build just broke everything with a "massive refactor"

### ISSUE THREAD

**Issue by steckerhalter** [quelpa/quelpa#143]
https://github.com/melpa/package-build/pull/15

**Comment by wasamasa** [comment]
How does the actual breakage look like? Did they remove functions we rely on? Did the signatures of such functions change? Do the functions do something completely different now?

If we can prove they broke API they shouldn't have, we could push back and get things fixed upstream.

**Comment by steckerhalter** [comment]
It looks pretty grim, yes Tarsius removed functions we rely on, see my build error here: https://travis-ci.org/steckerhalter/steckemacs.el/builds/358008890#L2259

 I'm still trying to wrap my head around it all. I guess it should be possible to adapt quelpa to the new state, but it takes time. I don't think they will be "fixing" things upstream because it works quite differently now.

**Comment by steckerhalter** [comment]
I wonder if we should just fork package-build using the commit before they removed all the useful fetchers. The only thing we would have to worry about would be changes to the recipe format which I guess are almost none.

**Comment by tarsius** [comment]
I am sorry I broke Quelpa and probably other downstreams.

At the same time I think that projects that build on top of `package-build` will benefit significantly in the long run if it moves away from merely incremental changes. But you might want to wait until v2 is released. So yes, you should probably downgrade to 1.1.

I don't plan to restore the removed fetchers but you could do so by implementing `package-build--checkout` methods. That wouldn't even have to be merged into `package-build`. But again you probably should wait a little longer before doing so (or do it on a feature branch, which is allowed to break occasionally).

**Comment by steckerhalter** [comment]
@tarsius no problem, we're probably better off not to depend on upstream package-build anyway, thanks

**Comment by steckerhalter** [comment]
Integrated version 1.1 of package-build into quelpa for now. It should work again. Leaving this open for now...

**Comment by steckerhalter** [comment]
@wasamasa if you want to have a look at adapting quelpa to the refactored pb, we could remove the v1.1 code again. I'd like to stick to the old code for now.
