### ISSUE TITLE
migrate to gitlab instance (framagit.org?)

### ISSUE THREAD

**Issue by steckerhalter** [quelpa/quelpa#148]
since microsoft aquires github I'd like to move the code

**Comment by steckerhalter** [comment]
yeah, I've reconsidered already :smile:  I'm moving to https://framagit.org/steckerhalter

**Comment by steckerhalter** [comment]
@wasamasa would you be happy with moving to framagit.org? maybe we can skip the quelpa org, I'd just put it under my user and give you access?

**Comment by wasamasa** [comment]
I don't particularly care. My last contribution is from almost a year ago, who knows when the next one will be. I'll let you know whenever I'll be needing access again.

**Comment by casouri** [comment]
So is the github repo still supported? Like a mirror?

**Comment by steckerhalter** [comment]
@casouri not sure yet, you'd want it to be mirrored?

**Comment by casouri** [comment]
A lot of people are still using GitHub so I think it would be nice to keep GitHub repo updated.

**Comment by jgkamat** [comment]
I'd reccomend putting a message on the top of the readme saying the repo is moved, if you plan to use https://framagit.org/steckerhalter/quelpa/ instead of this.

**Comment by steckerhalter** [comment]
yeah, I guess I'll setup a mirror and leave a message that people should use framagit.org to report issues etc.

**Comment by steckerhalter** [comment]
code moved and note added to README. it's now mirrored to github. I will disable issues here soon.

**Comment by Purring** [comment]
Do you plan on updating the Melpa recipie to point to Framagit? I don't think it really matters since this is a mirror so it technically works, but people may be confused about where to send issues (since reading readmes is hard ork)

**Comment by steckerhalter** [comment]
@Purring yeah, I made a PR. but know that you mention it. I shouldn't have mirrored the adapted code before it's merged :man_facepalming:

**Comment by steckerhalter** [comment]
good, I stopped the mirroring and reverted the code until it's merged

**Comment by steckerhalter** [comment]
melpa PR got merged. added a note the the readme. code is mirrored now. I'm going to disable issues since framagit should be used for that :tada:
