### ISSUE TITLE
Quelpa Maintenance Discussion

### ISSUE THREAD

**Issue by steckerhalter** [quelpa/quelpa#149]
Some people have offered to maintain and continue to develop quelpa. We're moving back to Github because of that and can discuss necessary steps on this issue.

**Comment by wasamasa** [comment]
You really should provide some description for this. The last thing I've read was this repository getting deprecated in favor of a GitLab thing.

**Comment by steckerhalter** [comment]
yeah, the whole discussion was here: https://framagit.org/steckerhalter/quelpa/issues/171

**Comment by alphapapa** [comment]
@steckerhalter Thanks for your flexibility and generosity.  Let me know what you'd like me to do to help maintain Quelpa.

**Comment by steckerhalter** [comment]
@alphapapa thanks. I've added you and @kiennq to the Members team which should give you write access and I think the ability to merge. Did you get an invitation?
I think Melpa should be informed that the sources of `quelpa` and `quelpa-use-package` have changed if someone wants to do that (by changing the recipes on their repo).

**Comment by steckerhalter** [comment]
As far as i'm concerned you both can go ahead, change, review and merge back what you think is good. If you have questions I can answer them of course.

**Comment by alphapapa** [comment]
I accepted the invitation, thanks.

I'll submit the changes to the MELPA recipes.

**Comment by steckerhalter** [comment]
:+1: :ok_hand:

**Comment by steckerhalter** [comment]
Thanks for participating in this discussion. I think we have a good way forward now and @alphapapa and @kiennq are doing a good at improving quelpa. I would suggest the following points for the collaboration:

- announce breaking changes and important improvements in the NEWS section of the README
- PRs should be small so that they can be merged in a reasonable time. if there is no consensus, a PR can probably be split up and some changes can be merged with the remaining PR focusing on the questionable parts

I'm closing this now, thanks!
