### ISSUE TITLE
ci/run.sh is dangerous

### ISSUE THREAD

**Issue by alphapapa** [quelpa/quelpa#160]
https://github.com/quelpa/quelpa/blob/62f4ee3065c46d670631d069f0d5850b371edd3e/ci/run.sh#L7

@steckerhalter I really think we should delete this file ASAP.  It runs `rm -rf ~/.emacs.d` in multiple places.  If anyone mistakenly runs this script locally, it will delete their Emacs config.

See #159 which replaces the Travis-based CI with one using `makem.sh` and GitHub Actions, which is safe to run both locally and on CI, as it runs Emacs in a temporary sandbox.

**Comment by steckerhalter** [comment]
the file is gone now
