### ISSUE TITLE
add CI status to README

### ISSUE THREAD

**Issue by steckerhalter** [quelpa/quelpa#167]
I have removed the Travis badge but would like to have a badge for the current CI. anyone knows how to do that?

**Comment by steckerhalter** [comment]
hmm or maybe it's not needed since the build status is signified on top now anyway...

**Comment by steckerhalter** [comment]
yeah I think that suffices

**Comment by tsuu32** [comment]
GitHub Actions provide svg badge for workflow such as `https://github.com/quelpa/quelpa/workflows/CI/badge.svg`.

**Comment by steckerhalter** [comment]
@tsuu32 thanks, well I'd say since the build status is now listed anyway on top it would be kind of redundant. I'm happy as long as there is some indication on the latest commit status.

**Comment by tsuu32** [comment]
I see. I'm OK.
