### ISSUE TITLE
Automatically uninstall deprecated package

### ISSUE THREAD

**Issue by kiennq** [quelpa/quelpa#169]
When upgrading new package with Quelpa, old package should be uninstalled automatically

**Comment by alphapapa** [comment]
@kiennq @steckerhalter This is not a good default.  New package versions may have bugs or adverse interactions with the user's configuration, and the user might need to revert to the older version.  But once the older version is deleted, the user no longer has that option.  `package.el` does not automatically delete old versions, so neither should Quelpa.

**Comment by kiennq** [comment]
When I update package via `list-packages`, I surely saw the obsoleted package being deleted right after updating to new package successfully. So I thought deleting the old packages is default behavior.

Should we create a new option to not delete obsoleted package?

**Comment by steckerhalter** [comment]
it is the default for package.el, yes and I would prefer to follow this behavior here too.
but to have an option for people that would like to keep the obsolete packages would be good too.

in general if a new version is buggy what a user should do is to pin the previously working version to a `:commit` or tag in the recipe

**Comment by alphapapa** [comment]
> it is the default for package.el

It's not quite that simple.  If a user presses `U` in the package list buffer, upgradable packages are marked for installation and existing versions are marked for deletion.  But if a user presses `i` to upgrade a certain package, the old version is not marked for deletion.

> in general if a new version is buggy what a user should do is to pin the previously working version to a :commit or tag in the recipe

If a user has installed a package from MELPA or ELPA with Quelpa, they won't have ready access to the package's git repo.  They would have to go look up the repo online.  Then they would not know which commit to pin, because the old version would have been deleted already, and there would be no way to know what the old version's commit was (and even if it hadn't been deleted yet, they'd have to find the commit hash by comparing each commit's timestamp to the timestamp of the old package version).

And all that assumes that the user knows how git works.

It's trivial to mark obsolete versions for deletion all at once, and disk space is not an issue, so it's not important to delete old versions automatically.  Doing so by default is not in the user's best interest.

**Comment by kiennq** [comment]
> It's trivial to mark obsolete versions for deletion all at once, and disk space is not an issue, so it's not important to delete old versions automatically. Doing so by default is not in the user's best interest.

The problem with this is that sometimes old package got loaded instead of newer one when Emacs start. That's annoying and sometimes may lead to disaster, especially if the old package behavior is destructive and user need to update to newer one to avoid that.

Given that the behavior of `U` in package list buffer is deleting obsoleted packages too, I think it makes sense to automatically remove obsoleted packages when user is trying to **update** packages.

How about using these new behaviors instead?
1. Have an option to allow user to silently delete obsoleted packages when update to newer one.
2. `quelpa-upgrade-all`, `quelpa-upgrade`, `C-u M-x quelpa` will try to delete obsoleted packages by asking user opinion while respecting 1.
3. `quelpa` by default will default not delete obsoleted packages while respecting 1.

With that we can archive both `U` behavior (via upgrading package) and `I` behavior (via installing package with `M-x quelpa`)

**Comment by steckerhalter** [comment]
> It's not quite that simple. If a user presses `U` in the package list buffer, upgradable packages are marked for installation and existing versions are marked for deletion. But if a user presses `i` to upgrade a certain package, the old version is not marked for deletion.

ok, I almost never even bother to use the `list-packages` interface and install my packages via init file where obsoleted packages are removed by `package.el` by default.

but trying it out, when I upgrade `hydra` with `i` in `list-packages` the old version was removed too:

```bash
~/.emacs.d/elpa $ ls -ld hydra-*
drwxr-xr-x   2          4096 2020-03-02 20:47 hydra-20200228.1830/
~/.emacs.d/elpa $ ls -ld hydra-*
drwxr-xr-x   2          4096 2020-03-04 08:38 hydra-20200303.1902/
```

I always found the obsoleted packages sticking around annoying. If there was an issue with a new version I'd usually dig in to find out the issue but I wouldn't just go back to use the obsoleted package. in addition as @kiennq points out it can lead to problems if multiple versions are present and sometimes the wrong version gets activated which is annoying too.

If I'd known how to delete obsoleted packages when I started quelpa I would have done that early on without leaving an option even to keep obsolete packages. but seeing that you (and maybe other people) would like to keep the current behavior I'd say we can add such an option to have quelpa retain obsoleted packages.

IMO the default should be changed to remove them by default (as it was merged). @kiennq already made an additional NEWS entry in #174.

@kiennq can you document this in the README if you add a flag like discussed? thanks

**Comment by kiennq** [comment]
I've made another PR and updates the doc there

**Comment by steckerhalter** [comment]
this should be fine then. thanks everyone for the work and contributions to the discussion :+1:
