### ISSUE TITLE
Current master some problem

### ISSUE THREAD

**Issue by tsuu32** [quelpa/quelpa#176]
Hello quelpa mentainers.
I updated quelpa to current master.
I feel some problem (but maybe there are not problem).

#### #166 is breaking change.

If I have old-style quelpa-cache file, `M-x quelpa quelpa-use-package` doesn't work.
old style cache:
((quelpa) (quelpa-use-package)...)

So I delete cache file. Is there another compatible way?

#### misleading message
I want to update posframe package so `C-u M-x quelpa posframe`.
Then I can see following message.
```
Package ‘posframe-20190407.2149’ deleted.
```

I feel weird but this is just user experience problem.

#### duplicated candidate
Currently `M-x quelpa` show all melpa package and installed package by quelpa.
So if I installed `quelpa-use-package` via quelpa, I can see two `quelpa-use-package` as candidates.
We should provide a way to distinguish them or `delete-dups`.

**Comment by kiennq** [comment]
> #### #166 is breaking change.
> If I have old-style quelpa-cache file, `M-x quelpa quelpa-use-package` doesn't work.
> old style cache:
> ((quelpa) (quelpa-use-package)...)
> 
> So I delete cache file. Is there another compatible way?

This's indeed seems to be a bug, can you check it again with #175?
As a side effect of reorder code structure in #175 to archive the change, it should fix the problem of old cache is not compatible with newer one.

 

> misleading message

The message means we've deleted the old `posframe` package. We should indeed suppress the echo of the message.



> duplicated candidate

I'm not experience this, did you use any package that advise `completing-read`?
I've tried with `helm` and with the vanilla `completing-read` seems there's no problem, the package always got deduplicated.

**Comment by tsuu32** [comment]
> This's indeed seems to be a bug, can you check it again with #175?
As a side effect of reorder code structure in #175 to archive the change, it should fix the problem of old cache is not compatible with newer one.

I checked #175 and can install quelpa-use-package via `M-x qulepa quelpa-use-package` with old quelpa cache.

> I'm not experience this, did you use any package that advise completing-read?
I've tried with helm and with the vanilla completing-read seems there's no problem, the package always got deduplicated.

Oh, sorry. I use ivy-mode (`ivy-completing-default`). So this is ivy-specific problem.

**Comment by steckerhalter** [comment]
so is it now ok with the new changes merged in?

**Comment by tsuu32** [comment]
@kiennq thanks for addressing the problem!

I don't mind ivy-specific issue.

**Comment by steckerhalter** [comment]
:+1:
