### ISSUE TITLE
Recipe format

### ISSUE THREAD

**Issue by steckerhalter** [quelpa/quelpa#178]
A few years ago Melpa started refactoring `package-build` which quelpa relied on to build the packages. I think support for all VCS tools except git was removed as well. I then decided to merge the last `package-build` code with support for all VCS into quelpa.

An advantage of this was that `package-build` would not break quelpa anymore (which happened a few times) and we got rid of a dependency.

On the other hand the Melpa recipes have probably evolved on their side and we still use the format as it was fixed then.

This is just something to keep in mind and we may want to have our own recipe format docs at some point.

**Comment by tsuu32** [comment]
Currently I tkink difference of `quelpa` arguments (`ARG` and `PLIST`) is maybe unclear.
Both of `(quelpa 'package-name :stable t)` and `(quelpa '(package-name :stable t))` are in README.
Clarification of quelpa recipe format will solve this.

This is related FIXME `stable` test  in quelpa-test.el. (Oh `stable` test name is in collision?)

**Comment by alphapapa** [comment]
It would probably be good to adhere as closely as possible to `package-build`'s recipe format and default recipe.  If package authors and users were to have to convert between them, it would likely put off many potential users.

**Comment by steckerhalter** [comment]
@alphapapa yeah. I think the main difference is that we support the old VCS and emacswiki while `package-build` does not anymore. I don't think it was an issue until now otherwise there would have been reports. 

I'm also thinking that melpa probably doesn't want to change the format because that would mean a lot of work if they'd have to adapt thousands of recipes. It's just good to keep it in mind.

**Comment by priyadarshan** [comment]
The non-profit I have been volunteering uses subversion (they recently moved from git, if that matters). 

All significant internal elisp code is now under svn. I know that melpa will not re-allowed svn fetcher, but is there a way to enable Quelpa to have it, or is `el-get` the only viable solution for now?

**Comment by kiennq** [comment]
Quelpa does allow you to use svn fetcher, the recipe should look like `(confluence :fetcher svn :url "https://svn.code.sf.net/p/confluence-el/code/trunk/" :files ("confluence*.el" "*.dtd" "*.xsl"))`

**Comment by priyadarshan** [comment]
Wonderful, thank you!

**Comment by alphapapa** [comment]
> The non-profit I have been volunteering with, uses subversion (they recently moved from git, if that matters).

They moved from Git to Subversion?

**Comment by priyadarshan** [comment]
I am glad one asked (usually people are bashed for even suggesting "old" systems). In their case, they spent a few months with a seasoned engineer, going through very thoroughly their use cases, and basically found all that what said [here](https://svnvsgit.com/) was true. (Sorry for the OT).

**Comment by alphapapa** [comment]
LOL, well, whoever wrote that web site certainly has a strong opinion against git:

> A year of using Git: the good, the bad, and the ugly, by Ivan Krivyakov, (2016)
> Unorthodocs: Abandon your DVCS and Return to Sanity, by Benjamin Pollack (2015)
> Proud to be a Moron – My Journey with Git, by Martin Kolb (2015)
> GIT: a Nightmare of Mixed Metaphors, by Jeffrey Ventrella (2013)
> 10 things I hate about Git, by Steve Bennett (2012)

**Comment by steckerhalter** [comment]
I worked on a bigger work project which was using svn. Each time I wanted to commit it was like a ritual. And I was scared to make a mistake and break the thing. With DVCS you can wipe out everything and it affects nobody. Later if you clean up the mess you can do a PR and a sane person reviews your shit. I don't miss you, SVN :laughing:

**Comment by priyadarshan** [comment]
It does not seems the case with this non-profit. But thanks, it is good to know.

**Comment by steckerhalter** [comment]
sure, everyone should use what they want and if they're happy with svn that's alright. it's certainly better than having no VCS which is still done even today in some companies

**Comment by steckerhalter** [comment]
I'm closing this since I don't think we need to do anything currently. If anyone feels motivated to better document how recipes work in quelpa (with examples for svn, mercurial etc.), go for it! :smile:
