### ISSUE TITLE
Incompatibility with auto-package-update

### ISSUE THREAD

**Issue by tastytea** [quelpa/quelpa#180]
`auto-package-update-now` from [auto-package-update](https://github.com/rranelli/auto-package-update.el) tries to upgrade all packages in `package-activated-list` from ELPA repositories, including quelpa packages.

I guess that should be mentioned in the readme?

See also: https://github.com/rranelli/auto-package-update.el/issues/42

**Comment by alphapapa** [comment]
Tools like that should not be assumed to be compatible with third-party package management tools, such as Quelpa.  It's not Quelpa's responsibility to document its compatibility, or lack thereof, with all such tools.

And, as I always say, automatically upgrading Emacs packages is a Bad Idea (TM), anyway.  You're asking for trouble.

**Comment by steckerhalter** [comment]
@tastytea I'd say if it can't be fixed for  `auto-package-update` then the readme of that package should mention the incompatibility, or if that is too much at least a notice that it might not work with other package managers.
