### ISSUE TITLE
:file source causes build failures when copying from a read-only filesystem

### ISSUE THREAD

**Issue by slippycheeze** [quelpa/quelpa#182]
For complicated reasons I build a package where the source is accessible via a local directory but where all files and directories are read-only.  

quelpa fails during building because `copy-directory` always preserves file, but importantly, directory permissions.  This leads to a read-only directory in `~/.emacs.d/quelpa/build/...`, which in turn breaks the build when it tries to write a stamp file.

quelpa should probably change the directory mode, or all modes, recursively after copy to allow writes by the current user.  

This problem may also apply when using a single file, because the call to `copy-file` requests that permissions be preserved, though I strongly suspect that single source file will never be written to.

**Comment by steckerhalter** [comment]
Hi! Looking at the code I don't think it's necessary to preserve file permissions really. At least I do not see any reason for it now so we might just drop the flag.

**Comment by steckerhalter** [comment]
but looking at the docs there's no way to instruct `copy-directory` not to preserve the file modes:

```
copy-directory is an interactive compiled Lisp function in ‘files.el’.

(copy-directory DIRECTORY NEWNAME &optional KEEP-TIME PARENTS
COPY-CONTENTS)

Copy DIRECTORY to NEWNAME.  Both args must be strings.
This function always sets the file modes of the output files to match
the corresponding input file.

The third arg KEEP-TIME non-nil means give the output files the same
last-modified time as the old ones.  (This works on only some systems.)

A prefix arg makes KEEP-TIME non-nil.

Noninteractively, the last argument PARENTS says whether to
create parent directories if they don’t exist.  Interactively,
this happens by default.

If NEWNAME is a directory name, copy DIRECTORY as a subdirectory
there.  However, if called from Lisp with a non-nil optional
argument COPY-CONTENTS, copy the contents of DIRECTORY directly
into NEWNAME instead.
```

**Comment by steckerhalter** [comment]
is the directory really read-only? because it seems that `copy-directory` which uses `copy-file` internally does not try to preserve the permissions

**Comment by steckerhalter** [comment]
can you please try to use `copy-directory` on your read-only directory to see if it retains the read-only permissions?

**Comment by steckerhalter** [comment]
can I close this or what is the status?

**Comment by dszakallas** [comment]
I have the same issue. I am using spacemacs that includes some local packages. I am insane, and I managing my spacemacs installation with nix, so the source files are in a read-only filesystem. During quelpa build, the files are copied to the build folder with their permissions preserved.
I opened a PR with a fix that solved the issue for me:
https://github.com/quelpa/quelpa/pull/261
