### ISSUE TITLE
issue installing `thingatpt+`

### ISSUE THREAD

**Issue by steckerhalter** [quelpa/quelpa#189]
For the record, this seems to have broken installing `thingatpt+` for me:
```emacs-lisp
(use-package thingatpt+
  :ensure nil
  :quelpa (thingatpt+
           :url "https://raw.githubusercontent.com/emacsmirror/emacswiki.org/master/thingatpt+.el"
           :fetcher url)) 
```
 Results in `Error (use-package): Cannot load thingatpt+` even though the file is correctly downloaded to the build directory, and evaluating it manually fixes the issue.

I tracked it down to `version` being `nil` in this function: 
```emacs-lisp
(defun quelpa-build (rcp)
  "Build a package from the given recipe RCP.
Uses the `package-build' library to get the source code and build
an elpa compatible package in `quelpa-build-dir' storing it in
`quelpa-packages-dir'.  Return the path to the created file or nil
if no action is necessary (like when the package is installed
already and should not be upgraded etc)."
  (let* ((name (car rcp))
         (build-dir (expand-file-name (symbol-name name) quelpa-build-dir))
         (version (quelpa-checkout rcp build-dir)))
    (if version
        (quelpa-archive-file-name
         (quelpa-build-package (symbol-name name)
                               version
                               (quelpa-build--config-file-list (cdr rcp))
                               build-dir
                               quelpa-packages-dir))
      (quelpa-build--message "Newer package has been installed. Not upgrading.")
      (when (fboundp 'package--quickstart-maybe-refresh)
        (package--quickstart-maybe-refresh))
      nil)))
```

Setting `(setq quelpa--override-version-check t)` fixes the issue. This PR sets the default to `nil`, which seems to be a breaking change.

_Originally posted by @mpereira in https://github.com/quelpa/quelpa/pull/187#issuecomment-644709715_

**Comment by mpereira** [comment]
Thanks for creating the issue @steckerhalter.

**Comment by kiennq** [comment]
`quelpa--override-version-check` is newly introduced variable, so this is not breaking change. The problem is that the logic in `quelpa-version-p` is not accounting for prerelease/beta/alpha/snapshot package, thus makes the installing of `thingatpt+` with version `0pre0.20200617.81650` failed.
