### ISSUE TITLE
Request for help producing recipe for GNU Hyperbole

### ISSUE THREAD

**Issue by rswgnu** [quelpa/quelpa#192]
We would like to get GNU Hyperbole installable via quelpa.  It is on Github and ELPA but not presently on Melpa.  The issue is that some code is in subdirectories of the package and must stay there when installed for proper installation, .e.g kotl/.  Additionally, the Info pages are below the directory man/.

The source is at:   www.github.com/rswgnu/hyperbole

Can you help by either producing a recipe that works or making updates to quelpa and/or melpa that allow for packages with multiple subdirectories?

**Comment by steckerhalter** [comment]
Hi. If you want to include some directories you can use a recipe like that:

```cl
(emojify :fetcher github :repo "iqbalansari/emacs-emojify" :files (:defaults "data" "images"))
```

in this case the dirs `data` and `images` should be added to the installation

**Comment by steckerhalter** [comment]
is this still a thing?

**Comment by rswgnu** [comment]
Yes, it is fully compatible with other current emacs packages as well.

-- Bob

**Comment by steckerhalter** [comment]
So yeah, as I have written you can add the folders with `:files` like I have written above, e.g.:

```cl
(hyperbole :fetcher github :repo "rswgnu/hyperbole" :files (:defaults "kotl" "man"))
```

that should be enough to include the subdirectories, if you want additional files you can add globs etc. as documented here: https://github.com/melpa/melpa#recipe-format

**Comment by rswgnu** [comment]
Sorry, I forgot about this thread.  Your recipe works great and is very helpful.

One last question.  I know there is some :upgrade parameter but it didn't do what I expected.  With some upgrade parameter, I'd like quelpa either install the package if not installed or upgrade it to the latest version of master or whatever branch is selected.  Maybe it is a use-package problem and I have to install quelpa-use-package but when I evaluated this, it would not upgrade the previously installed package to the latest:

(use-package burly
  :quelpa (burly :fetcher github :repo "alphapapa/burly.el" :upgrade t))

**Comment by kiennq** [comment]
What happens if you just eval `(quelpa '(burly :fetcher github :repo "alphapapa/burly.el" :upgrade t))`?
I think `quelpa-use-package` will not install/run `quelpa` command if package installed

**Comment by steckerhalter** [comment]
can we close this?
