### ISSUE TITLE
Silence "Newer package has been installed. Not upgrading."

### ISSUE THREAD

**Issue by pbeliveau** [quelpa/quelpa#193]
Is there a way to silence the quelpa message when a quelpa-build returns:
`Newer package has been installed. Not upgrading.`

I get this message multiple time at init, see *Messages* extract:
`Newer package has been installed. Not upgrading. [27 times]`

The source of the message is here:
[https://github.com/quelpa/quelpa/blob/master/quelpa.el#L281](https://github.com/quelpa/quelpa/blob/master/quelpa.el#L281)

**Comment by kiennq** [comment]
One way is to around advice `quelpa-build` with `inhibit-message` as `t`

**Comment by pbeliveau** [comment]
Followed your advice (no pun intended), and wrapped 'quelpa-build with someone else function. It works well and suppress the message. See: [Link to commit.](https://github.com/pbeliveau/.emacs.d/commit/1401e0ba2e0d38134807ba017c2aec9a32fe41aa)
