### ISSUE TITLE
Install with file other than .el file

### ISSUE THREAD

**Issue by jcs090218** [quelpa/quelpa#198]
I am trying to install my own package [jcs-elpa/impatient-showdown](https://github.com/jcs-elpa/impatient-showdown) and there is file `preview.html` but it doesn't get installed. 

Any idea? 😕

**Comment by kiennq** [comment]
You will need to setup your recipe to include `preview.html` in `:files`.
If you ever one to put your package to MELPA, this will be a good practice too.
For example, take a look at this recipe
``` elisp
(lsp-ui :repo "emacs-lsp/lsp-ui"
        :fetcher github
        :files (:defaults "lsp-ui-doc.html" "resources/*"))
```
Outside of default `.el` files, it also include `lsp-ui-doc.html` and files under `resources/*`

**Comment by jcs090218** [comment]
Thanks! I appreciated!
