### ISSUE TITLE
Problematic quelpa-cache

### ISSUE THREAD

**Issue by tsuu32** [quelpa/quelpa#200]
Hi,
Thanks for the maintaining quelpa!

Today I found `C-u M-x quelpa lsp-mode` doesn't upgrade lsp-mode package correctly.

Few days before, lsp-mode recipe in MELPA was changed (https://github.com/melpa/melpa/commit/525ea5927f1c66dc56b49aab40667be15a7ea063).
But `C-u M-x qulepa` uses old recipe in `quelpa-cache`, so installing fails.

https://github.com/quelpa/quelpa/blob/ed7ce05c85f5e24e7f434fca108a6c47f3e31dbf/quelpa.el#L1912-L1914
My suggestion is not to use `quelpa-cache` in `quelpa-interactive-candidate` in `quelpa` command.

If some users wants to upgrade packages which was installed by `(quelpa '(original recipe))`,  they can use `M-x quelpa-upgrade`.

**Comment by kiennq** [comment]
The problem is that if user install something not on MELPA, then delete it. After that user cannot install that package from `quelpa` again since `quelpa-cache` is not included in `quelpa-melpa-recipe-stores` anymore in `quelpa`.

We may need some more thoughts on this to support this scenario

**Comment by tsuu32** [comment]
> The problem is that if user install something not on MELPA, then delete it. After that user cannot install that package from quelpa again since quelpa-cache is not included in quelpa-melpa-recipe-stores anymore in quelpa.

I think such user installed the package via `(quelpa '(original recipe))` elisp not `M-x quelpa` command. 
Why does the user feel he/she want to install the package via `M-x quelpa` command.?

**Comment by kiennq** [comment]
> Why does the user feel he/she want to install the package via `M-x quelpa` command.?

Why not? Using the `(quelpa '(original recipe))` is lengthier way and not as nice as `M-x quelpa`.

Also if user mistakenly update custom recipe package via `C-u M-x quelpa`, it will overwrite custom package in `quelpa-cache`, resulted in updating a wrong package even with `quelpa-upgrade`.

Let see if we can simply resolve these problems before removing `quelpa-cache` from `M-x quelpa`

**Comment by tsuu32** [comment]
> Also if user mistakenly update custom recipe package via C-u M-x quelpa, it will overwrite custom package in quelpa-cache, resulted in updating a wrong package even with quelpa-upgrade.

Oh, I overlooked such a case... Yes, removing `quelpa-cache` from `M-x quelpa` is not good solution.

> Why not? Using the (quelpa '(original recipe)) is lengthier way and not as nice as M-x quelpa.

> Let see if we can simply resolve these problems before removing quelpa-cache from M-x quelpa

quelpa.el doesn't provide the function or user command which delete unneeded pakcage recipe from `quelpa-cache`.
In my case such function solves my problem.

**Comment by kiennq** [comment]
After thinking, I think it would be just fine to put `quelpa-cache` after `quelpa`.
That way + the default of `quelpa-upgrade-p` is `nil` will allow both:
- MELPA recipes are prioritized over temporary recipe defined with `M-x quelpa`.
- User would not accidentally update package by using `quelpa`
- Temporary recipe defined with `M-x quelpa` that's not in MELPA is still being installable via `M-x quelpa`

**Comment by kiennq** [comment]
@tsuu32 Can you check if #202 resolve your issue?

**Comment by tsuu32** [comment]
@kiennq thanks for doing this.
I confirmed #202's quelpa.el can install lsp-mode correctly even when `(lsp-mode :repo "emacs-lsp/lsp-mode" :fetcher github)` (which is old recipe) exists in `quelpa-cache`.
