### ISSUE TITLE
quelpa-upgrade lists only one package when two installed

### ISSUE THREAD

**Issue by condy0919** [quelpa/quelpa#205]
bootstrap `use-package` and `quelpa`:

``` emacs-lisp
;; Bootstrap `use-package'
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))
(eval-and-compile
  (setq use-package-always-ensure nil)
  (setq use-package-always-defer nil)
  (setq use-package-always-demand nil)
  (setq use-package-expand-minimally nil)
  (setq use-package-enable-imenu-support t))
(eval-when-compile
  (require 'use-package))

;; Bootstrap `quelpa'.
(use-package quelpa
  :ensure t
  :custom
  (quelpa-update-melpa-p nil)
  (quelpa-self-upgrade-p nil)
  (quelpa-checkout-melpa-p nil))

(use-package quelpa-use-package
  :ensure t
  :config
  (quelpa-use-package-activate-advice)
  :custom
  (quelpa-use-package-inhibit-loading-quelpa t))
```

I mainly use `quelpa` to install those packages not published in melpa.

``` emacs-lisp
;; LLVM IR
(use-package llvm-mode
  :ensure t
  :quelpa (llvm-mode :fetcher url
                     :url "https://raw.githubusercontent.com/llvm/llvm-project/master/llvm/utils/emacs/llvm-mode.el")
  :mode ("\\.ll\\'" . llvm-mode))

;; TableGen description
(use-package tablegen-mode
  :ensure t
  :quelpa (tablegen-mode :fetcher url
                         :url "https://raw.githubusercontent.com/llvm/llvm-project/master/llvm/utils/emacs/tablegen-mode.el")
  :mode ("\\.td\\'" . tablegen-mode))
```

But `quelpa-upgrade` only lists `llvm-mode`.

**Comment by kiennq** [comment]
This should be a bug in `package.el` that return `package-installed-p` for `tablegen-mode` as `nil`.

The reason is that `package-installed-p` is using `version<=` which is assume that `nil` version means `(0 0)`.
That is not actually correct since basically compare `nil` version to `(0 -1)`, the later should have higher version than the former one.

Can you report an Emacs bug for this?
In the mean time, I will look for a quick workaround in `Quelpa`

**Comment by condy0919** [comment]
Thanks for your quick reply.

> Can you report an Emacs bug for this?

The bug ticket https://debbugs.gnu.org/cgi/bugreport.cgi?bug=43260

**Comment by kiennq** [comment]
@condy0919 Can you check with #207?
Sorry for late fix.

**Comment by condy0919** [comment]
> @condy0919 Can you check with #207?
> Sorry for late fix.

Fixed, the issue has gone away. Thanks!
