### ISSUE TITLE
Is there a way to determine the branch for the local git fetcher?

### ISSUE THREAD

**Issue by publicimageltd** [quelpa/quelpa#208]
I turned to quelpa a while ago, and I don't regret it at all. I like it, and in particular I like that I can fetch my own little packages from my own git repositories (stored on my harddisk). So I can keep my packages under version control and work on them while still using the stable version. Thanks for this great package!

One lacuna there is, however. I _thought_ that the local git fetcher only fetches the `master` branch. But now I found out that it fetches the current branch, whatever it is. So my question is: Is there any way to tell quelpa to just fetch a specific branch? I know there's the `:stable` parameter, but that's not quite the same.

Here's an example setup:
```emacs-lisp
(use-package some-package
  :quelpa (some-package :fetcher git
		 :url "file://~/.emacs.d/lisp/git-packages/some-package")
  :bind
  (("<f12>" . some-package-do-something)))
```

I would imagine something like that:

```emacs-lisp
(use-package some-package
  :quelpa (some-package :fetcher git
                 :branch master
		 :url "file://~/.emacs.d/lisp/git-packages/some-package")
  :bind
  (("<f12>" . some-package-do-something)))
```

**Comment by tsuu32** [comment]
You say `:branch "branch-name"` doesn't work for local repo? 
Quelpa recipe format is compatible with [MELPA recipe format](https://github.com/melpa/melpa#recipe-format) so quelpa supports `:branch "branch-name"`.

**Comment by publicimageltd** [comment]
OK, RTFM. You are right. I looked for it in the quelpa documentation on github, I should have looked at the recipe format instead.
