### ISSUE TITLE
quelpa-git-clone-depth should not be used for "dumb" http repos

### ISSUE THREAD

**Issue by andreoss** [quelpa/quelpa#214]
`git clone` fails for "dumb" repositories such as `paredit`

Reproducible with:
```
(require 'package)
(package-initialize)
(unless (package-installed-p 'quelpa)
  (with-temp-buffer
    (url-insert-file-contents "https://raw.githubusercontent.com/quelpa/quelpa/master/quelpa.el")
    (eval-buffer)
    (quelpa-self-upgrade)))
(quelpa 'use-package)
(setq use-package-always-ensure t)
(setq use-package-ensure-function 'quelpa)
(use-package quelpa-use-package)
(use-package paredit)
```
Fails with
```
Cloning into '/home/a/.emacs.d/quelpa/build/paredit'...
fatal: dumb http transport does not support shallow capabilities
```

Workaround:
```
(setq quelpa-git-clone-depth nil)

```

**Comment by kiennq** [comment]
Quelpa shalllow clone might be too much and not really developer friendly.
With recent `git` we have [partial clone](https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/) which is also provide small repository size (like shallow clone) and developer friendly. Perhaps we should switch to use partial clone instead.
WDYT, @steckerhalter ?

**Comment by steckerhalter** [comment]
Sure if you wanna give this try
