### ISSUE TITLE
Feature request: `:patches` keywords

### ISSUE THREAD

**Issue by lebensterben** [quelpa/quelpa#217]
It's common that sometimes users want to install a modified version of a package.
Currently, the user needs to fork the package and host it somewhere (with or without version-control, remote or local, etc).

I propose to add a new keyword `:patches`, which accepts an ordered list of patch files represented as their local file path or remote locations. And `quelpa` would apply those patches, after checking out/downloading the upstream package but before building.

The advantage of using `:patches` over a fork is:
- Many modifications to upstream packages are trivial and `:patches` approach fits this AD-HOC nature very well.
- Often time users still want to keep updated with the upstream. Forking would require the user to take additional steps to keep it updated, while patching always download the latest upstream packages.
- Suppose users somehow managed to keep their forks updated, they still have the compatibility issue should there be any API changes in the upstream. Patching doesn't solve this, but it's a little bit more robust because it could fail during package build-time.

**Comment by steckerhalter** [comment]
hi. it's a good idea. I'm leaving this ticket open in case anyone wants to do a PR with this feature... cheers

**Comment by steckerhalter** [comment]
ok so I'm closing this... still think it would be a nice addition
