### ISSUE TITLE
Docs for :upgrade are confusing / inadequate

### ISSUE THREAD

**Issue by madscientist** [quelpa/quelpa#220]
I was using quelpa plus quelpa-use-package to install the latest cc-mode for a long time but sometime around last October it stopped working: I realized I've just been re-using the same version without any updates since then, and if I delete that version then quelpa doesn't install a new version.  All I see in my minibuffer is:
```
Newer package has been installed. Not upgrading.
```

I spent a lot of time this morning trying to work out what is happening.  Finally after much time in the elisp debugger I figured out that the `:upgrade` attribute has to be handled specially but this is not clear at all in the docs.

Based on the docs I was evaluating this:
```
(quelpa '(cc-mode :fetcher hg
                  :url "http://hg.code.sf.net/p/cc-mode/cc-mode"
                  :upgrade t))
```
But this does nothing.  After trial and error I discovered that the `:upgrade` must come AFTER the definition; this will work:
```
(quelpa '(cc-mode :fetcher hg
                  :url "http://hg.code.sf.net/p/cc-mode/cc-mode")
        :upgrade t)
```
It would be great if some kind of example for this would be added to the docs and/or the behavior of upgrade was more clearly explained.

I will file an issue with `quelpa-use-package` so they can figure out why their setting of `:upgrade` is not having any effect.

**Comment by kiennq** [comment]
@madscientist Can you help to create a PR for a new example? The current example is `(quelpa 'package-name :upgrade t)`, which make `:upgrade t` as a parameter of `quelpa` command instead of package definition (`package-name` in this case).
However, I do agree that is quite confusing.

**Comment by steckerhalter** [comment]
how's the status on this?

**Comment by steckerhalter** [comment]
closing because there was no reply
