### ISSUE TITLE
Unable to install packages with entry files organized under a directory

### ISSUE THREAD

**Issue by myTerminal** [quelpa/quelpa#224]
While installing packages with the `github` fetcher, usual packages work fine. One example is [theme-looper](https://github.com/melpa/melpa/blob/master/recipes/theme-looper), that works with the below script:

    (quelpa '(theme-looper :fetcher github
                           :repo "myTerminal/theme-looper"))

However, for packages that have their entry files organized into a directory other than the root of the repo, I haven't been able to do it. An example is [magit](https://github.com/melpa/melpa/blob/master/recipes/magit).

    (quelpa '(magit :fetcher github
                    :repo "magit/magit"))

This is because the file `magit.el` is stored inside a directory named `lisp` at the root of the repo.

I can use the `url` fetcher and have it as follows:

    (quelpa '(magit :fetch url 
                    :url "https://raw.githubusercontent.com/magit/magit/master/lisp/magit.el")

But then parts of the package are missing, for the relative file references inside the project.

Is there a way I can do that?

**Comment by kiennq** [comment]
Can you try to use magit recipe with `quelpa`? it should work

**Comment by myTerminal** [comment]
Running `(quelpa 'magit)` worked like a charm. So that means I can install MELPA recipes with quelpa as well? I'm sorry if this is obvious, but I might have missed it in the documentation.

**Comment by myTerminal** [comment]
I just re-read the documentation once again, and now I'm an even bigger fan of quelpa. Thank you for your super-quick help! I'll close this issue.

**Comment by contrapunctus-1** [comment]
I think I have the same problem, except I'm trying to use Quelpa to install Org from source. My configuration was -

```elisp
(use-package org
  :quelpa (org :fetcher git
               :url "https://git.savannah.gnu.org/git/emacs/org-mode.git"
               :files (:defaults "lisp"))
  ...)
  ```

But `org-version` would report that I was using v9.3, the one part of Emacs. An `"~/.emacs.d/elpa/org-2022..."` directory [^1] was present in `load-path`. Not sure how to proceed, since Org does not seem to have a recipe on MELPA.

[^1]: That's the one built by Quelpa, right?

**Comment by 2e0byo** [comment]
@contrapunctus-1 the magit recipe looks like this:

```lisp
(magit :fetcher github
       :repo "magit/magit"
       :files ("lisp/magit"
               "lisp/magit*.el"
               "lisp/git-rebase.el"
               "docs/magit.texi"
               "docs/AUTHORS.md"
               "LICENSE"
               (:exclude "lisp/magit-libgit.el"
                         "lisp/magit-libgit-pkg.el"
                         "lisp/magit-section.el"
                         "lisp/magit-section-pkg.el")
               ;; temporarily for stable:
               "Documentation/magit.texi"
               "Documentation/AUTHORS.md"))
```

You can easily build something similar for org (not that I've tried, mind...)
