### ISSUE TITLE
`quelpa-upgrade-all` seems to ignore `:stable` flag

### ISSUE THREAD

**Issue by myTerminal** [quelpa/quelpa#225]
Thanks for the wonderful package by the way!

Every time I upgrade all packages using `M-x quelpa-upgrade-all`, it upgrades all packages to the latest possible version, regardless of whether I specified installing only "stable" packages. Below is an example of how I install packages in my config:

    (quelpa workgroups2 :stable t)

This does produce the right results: installs the latest tagged version of `workgroups2`. However, when I run an overall upgrade using `quelpa-upgrade-all`, it does not remember the way I installed the packages earlier, and gets me the latest version and hence breaks my config. Is this intended?

**PS:** If this does happen to be the intended design, I do have a backup plan: using `:upgrade t` for all individual packages and have some packages update on every launch (or maybe limited using `quelpa-upgrade-interval`), but as I said, that's the backup plan.

**Comment by kiennq** [comment]
I guess you will need the customized recipe for `workgroup2` in this case.
For example, `(quelpa '(evil-escape :repo "kiennq/evil-escape" :fetcher github :stable t))`

**Comment by myTerminal** [comment]
I do have a pretty expressive config for how I fetch my packages, which is a mix of `url`, `github` and `melpa`. You may find them [here](https://github.com/myTerminal/.emacs.d/blob/1fdbe0aab73fb325b51286ed746794bda6897beb/emacs/myTerminal/basic/packages.el#L1) and [here](https://github.com/myTerminal/.emacs.d/blob/1fdbe0aab73fb325b51286ed746794bda6897beb/emacs/myTerminal/standard/packages.el#L1). I also use a helper function to set things up, which you can find [here](https://github.com/myTerminal/.emacs.d/blob/1fdbe0aab73fb325b51286ed746794bda6897beb/emacs/myTerminal/lib.el#L15).

At a high level, it seems to me that even with the `:stable` set as `t`, it seems to upgrade to non-stable package versions. I still have to try a few more things out, but just wanted to throw this out just in case.

**Comment by kiennq** [comment]
What's the value of your `quelpa-cache`?

**Comment by myTerminal** [comment]
`((ace-window :repo "abo-abo/ace-window" :fetcher github) (anzu :fetcher github :repo "emacsorphanage/anzu") (avy :repo "abo-abo/avy" :fetcher github) (buffer-move :fetcher github :repo "lukhas/buffer-move") (column-enforce-mode :fetcher github :repo "jordonbiondo/column-enforce-mode") (company :repo "company-mode/company-mode" :fetcher github :files (:defaults "icons")) (counsel-projectile :fetcher github :repo "ericdanan/counsel-projectile") (csharp-mode :fetcher github :repo "emacs-csharp/csharp-mode") (delight-1\.7 :fetcher url :url "https://elpa.gnu.org/packages/delight-1.7.el" :stable t) (diff-hl :fetcher github :repo "dgutov/diff-hl") (dired-ranger :fetcher github :repo "Fuco1/dired-hacks" :files ("dired-ranger.el")) (dired-subtree :fetcher github :repo "Fuco1/dired-hacks" :files ("dired-subtree.el")) (dumb-jump :repo "jacktasia/dumb-jump" :fetcher github) (eagle-eye :fetcher github :repo "myTerminal/eagle-eye" :stable nil) (emacs-daily-events :fetcher github :repo "myTerminal/emacs-daily-events" :stable nil) (emacs-home :fetcher github :repo "myTerminal/emacs-home" :stable nil) (emacs-visual-notifications :fetcher github :repo "myTerminal/emacs-visual-notifications" :stable nil) (fira-code-mode :fetcher github :repo "jming422/fira-code-mode") (golden-ratio :repo "roman/golden-ratio.el" :fetcher github) (green-phosphor-theme :fetcher github :repo "aalpern/emacs-color-theme-green-phosphor") (hemisu-theme :repo "andrzejsliwa/hemisu-theme" :fetcher github) (hydra :repo "abo-abo/hydra" :fetcher github :files (:defaults (:exclude "lv.el"))) (ibuffer-vc :repo "purcell/ibuffer-vc" :fetcher github) (js2-mode :repo "mooz/js2-mode" :fetcher github) (latex-preview-pane :fetcher github :repo "jsinglet/latex-preview-pane" :files ("*.el" "*.txt")) (magit :fetcher github :repo "magit/magit" :files ("lisp/magit" "lisp/magit*.el" "lisp/git-rebase.el" "Documentation/magit.texi" "Documentation/AUTHORS.md" "LICENSE" (:exclude "lisp/magit-libgit.el" "lisp/magit-libgit-pkg.el" "lisp/magit-section.el" "lisp/magit-section-pkg.el"))) (markdown-mode :fetcher github :repo "jrblevin/markdown-mode") (marmalade-client :fetcher github :repo "nicferrier/emacs-marmalade-upload" :stable nil) (material-theme :fetcher github :repo "cpaulik/emacs-material-theme") (mew :fetcher github :repo "kazu-yamamoto/Mew" :files ("*.el" "etc" "info/*.info*")) (minimap-1\.4 :fetcher url :url "https://elpa.gnu.org/packages/minimap-1.4.el" :stable t) (multiple-cursors :fetcher github :repo "magnars/multiple-cursors.el") (neotree :repo "jaypei/emacs-neotree" :fetcher github :files (:defaults "icons")) (outer-spaces :fetcher github :repo "myTerminal/outer-spaces" :stable nil) (overcast-theme :fetcher github :repo "myTerminal/overcast-theme") (projectile :repo "bbatsov/projectile" :fetcher github :files ("projectile.el")) (projectile-extras :fetcher github :repo "myTerminal/projectile-extras" :stable nil) (quelpa :repo "quelpa/quelpa" :fetcher github) (quickrun :repo "emacsorphanage/quickrun" :fetcher github) (rainbow-mode-1\.0\.5 :fetcher url :url "https://elpa.gnu.org/packages/rainbow-mode-1.0.5.el" :stable t) (ranger :fetcher github :repo "ralesi/ranger.el" :old-names (evil-ranger)) (restclient :repo "pashky/restclient.el" :fetcher github :files ("restclient.el")) (rust-mode :repo "rust-lang/rust-mode" :fetcher github) (sass-mode :repo "nex3/sass-mode" :fetcher github) (scss-mode :repo "antonj/scss-mode" :fetcher github) (skewer-mode :repo "skeeto/skewer-mode" :fetcher github :files ("*.html" "*.js" "*.el")) (sublimity :fetcher github :repo "zk-phi/sublimity") (telephone-line :repo "dbordak/telephone-line" :fetcher github) (theme-looper :repo "myTerminal/theme-looper" :fetcher github) (typescript-mode :fetcher github :repo "emacs-typescript/typescript.el") (undo-tree-0\.7\.5 :fetcher url :url "https://elpa.gnu.org/packages/undo-tree-0.7.5.el" :stable t) (volume :fetcher github :repo "dbrock/volume.el") (vue-mode :fetcher github :repo "AdamNiederer/vue-mode") (web-mode :repo "fxbois/web-mode" :fetcher github) (which-key :repo "justbur/emacs-which-key" :fetcher github) (window-shaper :fetcher github :repo "myTerminal/window-shaper" :stable nil) (workgroups2 :repo "pashinin/workgroups2" :fetcher github :files ("src/*.el")) (yaml-mode :repo "yoshiki/yaml-mode" :fetcher github) (yasnippet :repo "joaotavora/yasnippet" :fetcher github :files ("yasnippet.el" "snippets")) (zone-quotes :fetcher github :repo "myTerminal/zone-quotes" :stable nil) (zone-tunnels :fetcher github :repo "myTerminal/zone-tunnels" :stable nil) (ztree :fetcher github :repo "fourier/ztree"))`

This is effectively how I install `workgroups`:

    (quelpa workgroups2 :stable t)

Now that I see in the cache, even though I'm using the `:stable t` flag while installing `workgroups2`, it still appears to be without in the cache. Also, in seems to be converting the MELPA repo into a GitHub repo.

**Comment by myTerminal** [comment]
The other thing is, the `cache` seems to preserves the `:stable` flag only for the packages I install using from "github" or "url" . For the ones that I install from MELPA and I supply `:stable t`, it totally ignores that. Pretty much all other packages from MELPA have a missing `:stable` property.

**Comment by myTerminal** [comment]
I ran a few more tests, and found something interesting.

When I have `multiple-cursors` installed from MELPA, below is what makes it to the `quelpa-cache`:

    (multiple-cursors :fetcher github :repo "magnars/multiple-cursors.el")

However, when I switch to github instead, the entry for `multiple-cursors` looks like this:

    (multiple-cursors :fetcher github :repo "magnars/multiple-cursors.el" :stable t)

So (though I may be wrong), the `:stable` flag doesn't make it to the cache in the case of MELPA. If this makes sense (and is a valid gap), I can probably work on a pull-request?

**Comment by kiennq** [comment]
So for this one `(quelpa workgroups2 :stable t)`, the `:stable t` is flag for the `quelpa` command instead of as a part of the recipe for `workgroup2`. So it will not make it into the cached recipe.
If you're using your customer recipe like `(quelpa '(workgroup2  :fetcher ... :stable t))` then the `:stable t` will be part of the recipe and the `quelpa-uprade` will work properly.
I guess this is by design so that you can install the stable package as a one-off and then resume back to the normal `melpa` recipe.

I think what can be improved here is to let the usage of `(quelap '(workgroup2 :stable t))` becomes valid?
Meaning if the `recipe` doesn't contain `:fetcher` field, the recipe will be fetched from MELPA and we will merge the rest of the fields with what is in the recipe.
For example, if `workgroup2` has recipe of `(workgroup2 :fetcher github :repo "abc/abc" :files (:defaults "src/*.el"))`, then
``` elisp
(quelpa '(workgroup2 :files ("src/*.el") :stable t))
; expand the recipe to ===>
'(workgroup2 :fetcher github :repo "abc/abc" :files ("src/*.el") :stable t)
```

**Comment by myTerminal** [comment]
That makes sense. Currently, evaluating `(quelpa '(workgroup2 :stable t))` results in an error that says that it's not able to construct the method `quelpa-build--checkout-*`. Also, providing a `:fetcher` as "melpa" results in an error as there's no function named `quelpa-build--checkout-melpa` as there isn't any.

As a side note, back when I migrated from `package.el` to `quelpa`, I had to use "melpa" as the fetcher for quite a lot of the packages I installed because many of them didn't have ".el" files at the root of the project. Now that I read `:files ("src/*.el")` in your message, I think I should be able to fetch more packages from GitHub instead of MELPA. We might as well not need to change `quelpa` just for my use case. I'll post an update here soon.

Thanks for the explanation, it really helped!

**Comment by myTerminal** [comment]
I switched to "github" for all my packages now, and the only issue (as I mentioned) that was forcing me to use "melpa" was the source files not being at the root of the repos. [This change](https://github.com/myTerminal/.emacs.d/commit/b8a243aba9a478ca1c4c8c52594dc4689d3478db) fixes it. Thanks once again, @kiennq!
