### ISSUE TITLE
support subdirectories for the file fetcher

### ISSUE THREAD

**Issue by lafirest** [quelpa/quelpa#229]
I found that the file fetcher builds with path doesn't support subdirectories, but sometimes this is needed, maybe we should support this feature?

**Comment by steckerhalter** [comment]
subdirectories in what way? please include your use-case

```
(quelpa
 '(rainbow-mode :fetcher file
                :path "~/src/rainbow-mode"))
```

are you using something like this?

**Comment by lafirest** [comment]
> subdirectories in what way? please include your use-case
> 
> ```
> (quelpa
>  '(rainbow-mode :fetcher file
>                 :path "~/src/rainbow-mode"))
> ```
> 
> are you using something like this?

Thanks for your reply, but I've forgotten the use case, so sorry
