### ISSUE TITLE
Dependency not on Melpa

### ISSUE THREAD

**Issue by trev-dev** [quelpa/quelpa#231]
I am trying to install [ement.el](https://github.com/alphapapa/ement.el) which has a dependency of "taxy 0.9". This dependency does not exist on Melpa, but is on ELPA and non-gnu ELPA. Quelpa does not seem to be able to move past this. Is this working as intended?

**Comment by steckerhalter** [comment]
hi. quelpa needs the dependency defined somewhere. it can't know that it is somewhere else on it's own. so you either install the dependency before element.el or you add the recipe for taxy to `quelpa-melpa-recipe-stores`

**Comment by trev-dev** [comment]
I installed it prior to ement. It's just weird to me that it just worked with Quelpa not that long ago. The dependency is not new, and it still exists on Elpa. It's the goal for Quelpa to be package.el friendly. It may be a good idea for it to look at the repositories already set up for dependencies as a fall back?

**Comment by steckerhalter** [comment]
well the idea of quelpa is that the source code is used to build and install a packages (that's why it's called quelpa because "quelle" means source in german). if you want to install packages with the package manager you don't really need quelpa, or do you?

**Comment by steckerhalter** [comment]
but I think you can use `use-package` to mix both and install certain dependencies if you intend to do this the way you describe

**Comment by trev-dev** [comment]
After reflecting on this and your remarks I think I agree. Better to be explicit about a missing dependency on Melpa,  even though it exists in the official repository (Elpa).

I guess it just caught me a bit off guard. I pre-installed taxy ahead of time, problem is solved
