### ISSUE TITLE
Directory in :files Ignored with MELPA Recipe Format Example

### ISSUE THREAD

**Issue by LaurenceWarne** [quelpa/quelpa#236]
Hi, using the very last recipe example given in https://github.com/melpa/melpa/#example-multiple-files-in-multiple-directories:
```elisp
(pony-mode
 :repo "davidmiller/pony-mode"
 :fetcher github
 :files ("src/*.el" "snippets"))
```
Running:
```elisp
(quelpa '(pony-mode
          :repo "davidmiller/pony-mode"
          :fetcher github
          :files ("src/*.el" "snippets")))
```
Generates:
```
pony-mode-20170807.1622
├── pony-mode-autoloads.el
├── pony-mode.el
├── pony-mode.elc
├── pony-mode-pkg.el
├── pony-tpl.el
└── pony-tpl.elc
```
Whilst installing it from melpa generates:
```
pony-mode-20170807.1522
├── pony-mode-autoloads.el
├── pony-mode.el
├── pony-mode.elc
├── pony-mode-pkg.el
├── pony-tpl.el
├── pony-tpl.elc
└── snippets
    ├── html-mode
    │   ├── {{
    │   ├── bl
    │   ├── ex
    │   ├── for
    │   ├── if
    │   ├── loa
    │   ├── sup
    │   └── testc
    └── python-mode
        ├── auth-view
        ├── bn
        ├── model
        ├── modelform
        ├── render-to
        ├── testc
        ├── tra
```
I'm on Emacs 28.1 and I tried this on a fresh install of quelpa.

I assumed from the docs any melpa recipe would be compatible, alternatively please let me know if I'm doing something wrong, thanks.

**Comment by steckerhalter** [comment]
hey yes that's odd... I think it should pick up the folder. could be a bug.

**Comment by pjj** [comment]
FWIW, I don't think this is a bug in quelpa code, but rather in its README file.  It appears that the directory snippets/ is under src/, so the correct recipe would be:
```
(quelpa '(pony-mode
          :repo "davidmiller/pony-mode"
          :fetcher github
          :files ("src/*.el" "src/snippets")))
```

**Comment by steckerhalter** [comment]
@LaurenceWarne can you try with the recipe suggested by @pjj ?

**Comment by LaurenceWarne** [comment]
Yeah that works, thanks.  Perhaps it is just a documentation issue, it wasn't clear from me reading it whether the behaviour should always be consistent with melpa.
