### ISSUE TITLE
error: Version must be string

### ISSUE THREAD

**Issue by emacsomancer** [quelpa/quelpa#243]
Since the latest update, any attempts to use quelpa to update seem to result in error `error: Version must be a string`.

**Comment by schspa** [comment]
> Since the latest update, any attempts to use quelpa to update seem to result in error `error: Version must be a string`.

I have make a PR for this problem.  @@
https://github.com/quelpa/quelpa/pull/244

**Comment by steckerhalter** [comment]
Ok thanks I'm going to merge the PR. We haven't got a proper tests working anymore and I'm busy with other things so if anyone would volunteer to fix the tests that would be great. Cheers

**Comment by steckerhalter** [comment]
this is fixed right?
