### ISSUE TITLE
Unrecognized keyword: :quelpa

### ISSUE THREAD

**Issue by drewwells** [quelpa/quelpa#246]
I have not had luck installing this with quelpa. I get the error in the subject.

**Comment by steckerhalter** [comment]
hey what's the whole command you are using?

**Comment by drewwells** [comment]
Install instructions for this project, I assume I have done something wrong with quelpa install though. https://github.com/zerolfx/copilot.el
```
(use-package copilot
  :quelpa (copilot :fetcher github
                   :repo "zerolfx/copilot.el"
                   :branch "main"
                   :files ("dist" "*.el")))
;; you can utilize :map :hook and :config to customize copilot
```

**Comment by kiennq** [comment]
You will need `https://github.com/quelpa/quelpa-use-package` to use `:quelpa` with `use-package`

**Comment by steckerhalter** [comment]
Hey I think @kiennq is correct. Is that ok for you?
