### ISSUE TITLE
Figure out why the build fails with Emacs 28.2 and Snapshot

### ISSUE THREAD

**Issue by steckerhalter** [quelpa/quelpa#250]
If anyone is up for the task, it would be great. Seems to be because it can't compile `quelpa-test.el`. I removed 28.2 and snapshot so there is at least a working build

**Comment by jcs090218** [comment]
I have tried it with Eask; everything seems to be okay (all green). See https://github.com/jcs-PR/quelpa/pull/1 (please ignore the windows snapshot for now; there is an error in that snapshot which is an upstream error and not from this package).

According to https://github.com/quelpa/quelpa/pull/240#issuecomment-1672002786, I think we just need to remove `test/quelpa-test.el` from the compile queue. 🤔

**Comment by steckerhalter** [comment]
Or we can just use Eask? I think that would be a good option if you'd like to make a PR

**Comment by jcs090218** [comment]
👍 I have opened a PR in #251.
