### ISSUE TITLE
Seeking new maintainer?

### ISSUE THREAD

**Issue by alphapapa** [quelpa/quelpa#252]
Hi @steckerhalter,

I just noticed this line in the readme:

> 2023/08/09: I’m looking for a new maintainer since I’m almost not using Emacs anymore /steckerhalter

What's the current status?

**Comment by steckerhalter** [comment]
Thanks @alphapapa 
There's noone really maintaining quelpa in the proper sense  at the moment. So that's the current status 😌

**Comment by alphapapa** [comment]
Well, I still use it every day, so if you don't intend to return to maintaining it, I'm willing to adopt it.

**Comment by steckerhalter** [comment]
Oh, I think you're already part of the team. Let me know if you need more permissions.

**Comment by alphapapa** [comment]
Yes, I already have commit rights.

What I mean is, if you'd like me to "adopt" it, that would mean taking full responsibility for and ownership of it.  I'd want to move the repository to my GitHub account so I can more easily monitor it for notifications (which GitHub's notification filters allow me to do for repos under my account, but not others), and so I would have full control over, e.g. who else had commit rights.  IOW, the same as I said a few years ago here: https://github.com/quelpa/quelpa/issues/164#issuecomment-591763940

If you want to retain ownership of it, of course, that's up to you, but in that case I can't take responsibility for the package, which is what "adoption" means to me.  So that would seem to mean maintaining the status quo (i.e. if I notice a problem, I might commit a fix; and if someone pings me on an issue, I might chime in; otherwise, it's just one of many repositories I have some kind of interest in).

Whatever you decide is fine.  Thanks for your work on Quelpa.

**Comment by jcs090218** [comment]
I thought @kiennq and I were maintainers of this package... 🤔 I like to co-maintain packages with @kiennq since he's one of the elisp developers I trust (we're both maintainers at `lsp-mode`). I'm less active on this repo since I've no problem using the package and consider stable enough for everyday use. But if something goes wrong, I'll fix it.

Anyway, I prefer to have this repo stay with this organization. I don't want to navigate to other people's GitHub accounts to maintain a repository. 😕

**Comment by steckerhalter** [comment]
Thanks for your comments. Well when I wrote that I'm looking for a maintainer I meant that I was looking for someone who volunteers to continue the development of quelpa, that is not just maintaining the status quo, but improving the current code, implement new features, streamline the package and release regular updates as it is the case with most other packages. As far it goes for the status quo I think @jcs090218 is right, that he and @kiennq volunteered to maintain it so I think this is already covered. Also I believe if someone steps up to do regular updates as I have pointed out, then I could make this person an additional owner of the org. Also to move the repo to some other place would be difficult because the url would have to be changed everywhere and many things would break for many people which is unnecessary IMO. So sorry for the confusion. I'll update the notice in the readme to make this clearer. Thanks!

**Comment by alphapapa** [comment]
@steckerhalter 

> I was looking for someone who volunteers to continue the development of quelpa, that is not just maintaining the status quo, but improving the current code, implement new features, streamline the package and release regular updates 

Those kind of changes tend to require someone with vision to drive the project forward, and that's often not compatible with team development.  In the case of this project, so far, there hasn't been much in the way of team development.  In fact, major changes have been made without consulting other the maintainers, which is the antithesis of teamwork.  

For myself, I certainly wouldn't try to implement major changes like you're hoping for that way; and if the other members of the team do, that would preclude me from trying to do so myself, as at any time, my changes might get undone (as has already happened), which would make the time I had spent a waste.  (I have no interest in arguing about changes to a package like this.)

> as it is the case with most other packages

IME, *most* packages don't see regular updates.  A relatively small subset do, depending on their purpose.  For a package like Quelpa, it's probably to be expected that it will reach a state where most of the work on it is fixing occasional compatibility issues that arise as related software is developed; IOW, it should reach the point where it is mostly "done."  And I think Quelpa has mostly reached that state of maturity, so it *shouldn't* see much in the way of changes (which always brings the risk of introducing bugs)--and that should be considered a good thing.

> As far it goes for the status quo I think @jcs090218 is right, that he and @kiennq volunteered to maintain it so I think this is already covered.

You may recall that I also did that, four years ago when we had a similar discussion.  Even then, it was made clear that @kiennq wasn't interested in team development, as he said he would merge changes after giving me only one day to review them myself.  (Imagine if Emacs itself were developed that way.)  Since then, @jcs090218 has also made significant changes without discussion.

Is this really a healthy status quo?  It seems less like directed development with a vision of the package's purpose and future, and more like a few people making changes when and how it suits them personally.

Well, as I said, it's your package, so if this is how you want it, that's up to you.  However, if you'll permit me to say: if you really are moving on from Emacs usage and maintenance of related projects, it probably would behoove the projects in question if you truly let someone else take the reins (meaning full responsibility, i.e. ownership).  It's often "unhealthy" for projects like this to live under the shadow of their original author who has all but officially retired.  Letting go isn't easy, I know, but like parenting people, at some point, it's for the best.

**Comment by steckerhalter** [comment]
Hey sorry I didn't remember that we had talked about this already. I'm not aware that there were changes made without a discussion. I prefer to let people do something if they are motivated and not stand in the way. If you have objections then please raise them.

As for what I was talking about, I didn't mean breaking (major) changes should be made but I was talking about updates, to make things smoother and more convenient for the user. I believe there is a lot that could be done still. So I would say the way forward would be to make milestones, issues, PRs etc. If someone would like to do something in this direction.

When it comes to bugfixing I think there are enough people who offered help so I don't think there's a need to change anything. There hasn't been any activity for a while and so either people are not using quelpa anymore or it "just works" :smile: 

I hope you have a nice day

**Comment by steckerhalter** [comment]
I removed the message which said that I'm looking for a "maintainer" since it wasn't clear what my intention was

**Comment by alphapapa** [comment]
Ok, thanks for clarifying your intentions and plans.
