### ISSUE TITLE
Add support for stable MELPA packages

### ISSUE THREAD

**Issue by wasamasa** [quelpa/quelpa#42]
MELPA finally approached Marmalade with that feature. [See this commit](https://github.com/milkypostman/melpa/commit/b350df249cd124fc376e991e57e9d072d490a072). I envision this as an extra keyword that only does something when specifying a MELPA recipe.

    (quelpa 'magit :stable t) ; grabs stable release
    (quelpa '(magit) :stable t) ; grabs stable release, too
    (quelpa '(magit :hurr durr) :stable t) ; ignores it when a custom recipe is used

**Comment by steckerhalter** [comment]
who wants stable stuff anyway?

**Comment by steckerhalter** [comment]
All it needs to build stable is:

```cl
(let ((package-build-stable t))
  (quelpa '(magit :fetcher github :repo "magit/magit")))
```

why should it be ignored on a custom recipe?

**Comment by wasamasa** [comment]
You're right, on custom recipes tags may be used as well.  I assume my intent when I've opened this ticket was providing an extra option additionally to the existing `:update` one that modifies the build behaviour.

**Comment by wasamasa** [comment]
Any special updates now that the referenced task is complete?

**Comment by steckerhalter** [comment]
done with #68
