### ISSUE TITLE
`\.\.\.` ends up in cache

### ISSUE THREAD

**Issue by wasamasa** [quelpa/quelpa#51]
Where does it come from? What does it mean? It definitely shouldn't be there and seems to be the last thing in the cache as everything after that is truncated.

**Comment by wasamasa** [comment]
Did this get magically fixed or why did you decide to close nearly every issue that was left open?

**Comment by steckerhalter** [comment]
clean slate kind of thing. feel free to reopen if you want to work on somehing :)

**Comment by steckerhalter** [comment]
but don't bother if it's just to keep issues open and not doing anything...

**Comment by wasamasa** [comment]
Thanks for the information, would be a good idea to reopen them once I'm on to something since my elisp skills substantially improved compared to when I started working on Quelpa.

**Comment by steckerhalter** [comment]
sure, if you'd like to work on an issue, reopen it. I can do some reviewing etc.

**Comment by wasamasa** [comment]
I have a horrible suspicion why it happens.

I'm using `prin1-to-string` to serialize the list of cache items which is subject to truncation as determined by `print-level` and `print-length`.  This doesn't explain why it happens in the first place (both variables seem to be unset in both Emacs 24.3 and 24.4), but could be a plausible explanation. It's time to reopen this!

**Comment by wasamasa** [comment]
Let's hope this never happens again to me.
