### ISSUE TITLE
Error on some packages: Package lacks a "Version" or "Package-Version"

### ISSUE THREAD

**Issue by bricewge** [quelpa/quelpa#66]
Installing `outorg` from `quelpa` fail. But it is present in MELPA, installing it from there work and also with `package-install-file`. Moreover the "Version" it complain about is already present in `outshine.el`. I get the same issue when installing `outorg-export`.

Evaluating `(quelpa '(outorg) :upgrade t)` give me the following return by the debugger:
```
Debugger entered--Lisp error: (error "Package lacks a \"Version\" or \"Package-Version\" header")
  signal(error ("Package lacks a \"Version\" or \"Package-Version\" header"))
  error("Package lacks a \"Version\" or \"Package-Version\" header")
  package-buffer-info()
  byte-code("\303\304!rq\210\305\216\306	!\210\n\307=\203
```

**Comment by steckerhalter** [comment]
I can't reproduce the issue with outorg yet (install works), but outorg-export also fails for me. I think it has something to do with the `~/.emacs.d/quelpa/packages/outorg-export-readme.txt` (which of course doesn't have a file header, but I'm not yet sure.

**Comment by steckerhalter** [comment]
nope, that wasn't the case. 

the problematic code is:

```cl
(with-temp-buffer
  (insert-file-contents-literally "~/.emacs.d/quelpa/packages/outorg-export-20150212.1459.el")
    (package-buffer-info))
```

Isolated from https://github.com/quelpa/quelpa/blob/master/quelpa.el#L159

When I try to open the file manually it asks me about local variables that are risky and I need to confirm the loading, I think that might be the issue here.

**Comment by steckerhalter** [comment]
The code for `package-buffer-info` (emacs internal function) tries to find the package header like this:

```cl
  (unless (re-search-forward "^;;; \\([^ ]*\\)\\.el ---[ \t]*\\(.*?\\)[ \t]*\\(-\\*-.*-\\*-[ \t]*\\)?$" nil t)
    (error "Package lacks a file header"))
```

And this seems to fail for `outorg-export.el` so there's something fishy with that header:

```cl
;;; outorg-export.el -- Automated exporting through org

;; Author: Jonathan Leech-Pepin <jonathan.leechpepin AT gmail DOT com
;; Version: 20150212.1459
;; X-Original-Version: 0.1
;; URL: https://github.com/jleechpe/outorg-export
...
```

**Comment by wasamasa** [comment]
It's missing the third dash?

**Comment by steckerhalter** [comment]
@wasamasa yes, I think that's the issue.

```
The very first line should have this format:

     ;;; filename --- description
```

from http://www.gnu.org/software/emacs/manual/html_node/elisp/Library-Headers.html

**Comment by steckerhalter** [comment]
@bricewge for outorg, can you remove it with `M-x list-packages` and try like that:

```cl
(quelpa 'outorg :upgrade t)
```

**Comment by bricewge** [comment]
My bad I didn't test this on a clean `.emacs.d` without my config.
I had already found the missing dash earlier but it didn't solve the issue when my config is loaded and this kind of issue should return `"Package lacks a file header"`.
Looks like the issue come from my side. Sorry for this inconvience.
