### ISSUE TITLE
Magit next branch need to be compiled with make

### ISSUE THREAD

**Issue by bricewge** [quelpa/quelpa#71]
I need to use the coming 2.1 version of Magit, so I was using this `(quelpa '(magit :repo "magit/magit" :branch "next" :fetcher github) :upgrade t)`. Unfortunately this is now throwing this issue `error: Required feature 'magit-autoloads' was not provided` and to generate the `magit-autoloads` you need to use `make` which Quelpa can't do as far as I know.

The use of `make` in Quelpa has already been mentioned in #35 and #29. So my workaround for this is to use my system package management to install Magit.

**Comment by wasamasa** [comment]
How exactly does MELPA build Magit then, considering their policy on using Make?

**Comment by steckerhalter** [comment]
I use the next branch myself and it works without an issue. Be sure to remove old magit versions first and also git-* modes. Then restart emacs so there is nothing left of the old magit.

**Comment by bricewge** [comment]
@steckerhalter: I just did what you said, it doesn't fix the issue, I still get the same error. Did you update magit recently? I only stumble upon this error some days ago.

@wasamasa: I don't know, you should ask @tarsius if you want to know how they will build magit-2.1 for MELPA.

**Comment by steckerhalter** [comment]
@bricewge yes, I switched to `next` 4 days ago.  just tried again. that change must have happened in the meantime then.

**Comment by steckerhalter** [comment]
I don't understand why magit is building an autoload file via make and then requiring that. Aren't autoloads just working without any further ado?

Maybe @tarsius can say more about that :smile:

**Comment by steckerhalter** [comment]
my workaround:

```cl
(quelpa '(magit :fetcher github :repo "magit/magit" :commit "2958790"))
```

using `next` just before the makefile change was introduced

**Comment by tarsius** [comment]
Well that change comes with a length commit message: https://github.com/magit/magit/commit/0fb98c2c89ce9e94301f7f3b671f255fbc3c3e9a. Note especially the last bullet point. Since the Makefile is not relevant (should not be) when using `package.el` it boils down to:

```lisp
(cl-eval-when (load eval)
  ...
  (unless (require 'magit-autoloads nil t)
    (require 'magit-ediff)
    (require 'magit-wip)
    (require 'magit-backup)
    (require 'magit-extras)))
```

This should not be evaluated when compiling `magit.el`. When compiling another file it unfortunately is, but `magit-autoloads` is soft required, so it should not matter if it doesn't exist. I don't use Elpa so any help is appreciated figuring out why this change causes issues. So far I don't see how the reported error could possibly happen.

**Comment by tarsius** [comment]
> I don't understand why magit is building an autoload file via make and then requiring that. Aren't autoloads just working without any further ado?

Autoloads only do something if they are loaded obviously - if one does not use Elpa then that does not happen automatically. So magit does it itself, but if that fails it just loads the remaining libraries as a fallback (or at least that was the intention). These libraries have to be either loaded or autoloaded because the commands they define are used in `magit-mode-map`.

**Comment by steckerhalter** [comment]
yes, I was referring to ELPA compiling automatically. the weird thing is that the soft-require is causing an error (I was looking into that but made a mistake and thought it's hard-required). so that might even be an Emacs bug,

**Comment by steckerhalter** [comment]
@tarsius great work btw on magit, thanks for that

**Comment by steckerhalter** [comment]
![screenshot from 2015-04-08 20 43 19](https://cloud.githubusercontent.com/assets/3024024/7052544/85bc5a56-de2f-11e4-846c-ba50ef50d254.png)

**Comment by tarsius** [comment]
Ah, I think that happens when a file exists, but does not provide the appropriate feature.

**Comment by steckerhalter** [comment]
@bricewge the correct recipe for magit `next` seems to be (works for me with HEAD):

```cl
(quelpa '(magit :fetcher github :repo "magit/magit" :files ("*.el" (:exclude "magit-autoloads.el"))))
```

`magit-autoloads.el` has to be excluded because it causes the above error (it's only needed when using `make` and not with ELPA)

**Comment by tarsius** [comment]
That  should do it: https://github.com/magit/magit/commit/1219202e8937128fdc4cc9e87400a8aa232917fd

@steckerhalter I don't think what you are doing is correct. `magit-autoloads.el` isn't a file tracked in thhe git repository. It generated by `package.el` (apparently without containing a `provide` from).

**Comment by steckerhalter** [comment]
@tarsius ok, thanks. the :exclude does not alter the checkout but makes he build process ignore that file so in then end it does not end up in the .tar and hence doesn't cause the error

but your fix doesn't make that necessary I guess

**Comment by steckerhalter** [comment]
confirmed that now it also works with:

```cl
(quelpa '(magit :fetcher github :repo "magit/magit"))
```

**Comment by bricewge** [comment]
Thanks all! Magit 2.1 is now working fine with Quelpa. 
``` lisp
(quelpa '(magit :fetcher github :repo "magit/magit" :branch "next"))
```
