### ISSUE TITLE
Quelpa use and self-upgrading does not work on Windows.

### ISSUE THREAD

**Issue by jaccarmac** [quelpa/quelpa#72]
In attempting to move from a Unix to a WIndows environment while keeping my Emacs configuration, I have run into a series of problems with my use of Quelpa in my `init.el`. I am using the Windows build of Emacs, not the Cygwin version.

The first error I ran into was with some code in `package-build` not being able to find the `env` command. I traced it to [this line](https://github.com/milkypostman/melpa/blob/f4d5f3829c992457eb552202fd3d42cbc8c7cd89/package-build.el#L224) of `package-build.el`. This problem was very easy to resolve by installing Cygwin and adding its `bin` directory to my path. It may even be only tangentially related to the next issue, but I think it may be relevant and will bring it up again later.

The more pressing issue is my inability to install any packages using the `quelpa` function, interactively or programmatically, from a `*scratch*` or from `init.el`. The problem is on [this line](https://github.com/jaccarmac/dot-emacs-dot-d/blob/4d32596a8652c34f189c27b3cdad15c888c555fa/init.el#L9) of my configuration, and throws the same error mentioned in #66. However, `use-package.el` is in fact [well-formed](https://github.com/jwiegley/use-package/blob/39f02a177c58756977166472445e68c0ced2fe72/use-package.el#L1).

Quelpa also fails to self-upgrade, erroring out when trying to unpack a tarball in `~/.emacs.d/quelpa/packages` which does not exist.

I'm relatively sure that Windows line endings are not a problem, as the patch to fix interoperability in `package.el` happened sometime in [2010](https://groups.google.com/forum/#!msg/clojure/xNALoPFhTEk/v8iwn-8ETjsJ). I'm at a dead end as far as troubleshooting goes, unless for some reason the fact that `LC_ALL` is not set properly on the Windows side is causing something to blow up. See #65.

**Comment by steckerhalter** [comment]
I tried to use it with the Windows build (24.4) too but gave up after getting to this weird tar problem you also describe.

The Windows build also had an error with SSL and couldn't clone git (I fixed that somehow). Is that now ok?

I switched to the cygwin build which worked for the most part but I didn't have to use Windows to code afterwards (privately I only have and use GNU!/Linux).

I will check with the latest Windows build again...

**Comment by jaccarmac** [comment]
The SSL error is due to missing DLLs, which you have to "patch" (as in copy the files into your installation) manually. Bummer if Cygwin is the only way to make it work; I've used it in the past but it has problems of its own.

**Comment by steckerhalter** [comment]
The culprit seems to be in the function pb/build-multi-file-package: https://github.com/milkypostman/melpa/blob/master/package-build.el#L1164

It returns the path to the built .tar but the tar isn't really there so later on quelpa cannot open the tar file of course.

**Comment by steckerhalter** [comment]
I also found out that installing git for windows with the option of making additional unix tools available does provide `env` without any further steps necessary.

**Comment by steckerhalter** [comment]
so after some more digging here is the problem:

```
"c:/Program Files/Git/bin/tar.exe": Cannot execute remote shell: No such file or directory
"c:/Program Files/Git/bin/tar.exe": c\:/Users/foobar/AppData/Roaming/.emacs.d/quelpa/packages/quelpa-20150516.1329.tar: Cannot open: I/O error
"c:/Program Files/Git/bin/tar.exe": Error is not recoverable: exiting now
2015-05-16 13:29:19 +0200
```

tar fails...

**Comment by steckerhalter** [comment]
```cl
(defun pb/create-tar (file dir &optional files)
  "Create a tar FILE containing the contents of DIR, or just FILES if non-nil."
  (when (eq system-type 'windows-nt)
    (setq file (replace-regexp-in-string "^\\([a-z]\\):" "/\\1" file)))
  (apply 'process-file
         package-build-tar-executable nil
         (get-buffer-create "*package-build-checkout*")
         nil "-cvf"
         file
         "--exclude=.svn"
         "--exclude=CVS"
         "--exclude=.git*"
         "--exclude=_darcs"
         "--exclude=.fslckout"
         "--exclude=_FOSSIL_"
         "--exclude=.bzr"
         "--exclude=.hg"
         (or (mapcar (lambda (fn) (concat dir "/" fn)) files) (list dir))))
```
rewrites the path so `c:/` is turned into `/c/`

**Comment by steckerhalter** [comment]
but that's not the end of the story. the next problem is indeed the windows file encoding. in quelpa we do the same thing like here in the emacs core:

```
(defun package-install-file (file)
  "Install a package from a file.
The file can either be a tar file or an Emacs Lisp file."
  (interactive "fPackage file name: ")
  (with-temp-buffer
    (insert-file-contents-literally file)
    (when (string-match "\\.tar\\'" file) (tar-mode))
    (package-install-from-buffer)))
```
then we (and emacs core) use `(package-buffer-info)` to get the info. but on windows the line endings make that fail hence you get "package lacks a version...".

to sum it up:

melpa's `package-build` would need to be fixed, then these places where `insert-file-contents-literally` is followed by `package-buffer-info` (emacs core `package.el` and `quelpa`)

**Comment by steckerhalter** [comment]
After pondering this a bit more I found further issues with line-endings. I don't think it makes much sense trying to fix all of this when the Cygwin build pretty much works out of the box.

I'm going to advice that people use the Cygwin build and will write a few instructions how to install that.

**Comment by steckerhalter** [comment]
## Emacs Installation Instructions for Windows:

### Install Cygwin

Download either the 64-bit or 32-bit setup file from http://cygwin.com/install.html
It is usually better to install Cygwin just for the current user, not system-wide.

- open the location where you downloaded the setup executable
- press shift and right-click -> open command prompt here

Run for example:

    setup.exe --no-admin

Just leave the default packages selected and finish the installer.

### Install a sane package manager

Install apt-cyg from https://github.com/transcode-open/apt-cyg:

Open the Cygwin terminal and execute:

    lynx -source rawgit.com/transcode-open/apt-cyg/master/apt-cyg > apt-cyg
    install apt-cyg /bin

### Install Emacs

Then install Emacs like this:

    apt-cyg install wget git tar emacs-w32 emacs-el

This will take quite a while...

### Fix issue on 32-bit Cygwin

Using the 32-bit version of Cygwin I got weird vfork errors and had to a *rebase* (see http://cygwin.wikia.com/wiki/Rebaseall):

- close Cygwin terminal
- Start/Run: "C:\cygwin\bin\dash.exe"
- run: /bin/rebaseall -v
- close dash

### Enjoy

So then everything should work with quelpa. Open the Cygwin terminal, install your init file and enjoy Emacs (even with `emacs --daemon` available on Windows)

**Comment by steckerhalter** [comment]
@jaccarmac I had an idea yesterday. The EOL problems are due to Git for Windows checking out the repos with CRLF which is the default setting (in the installer). If you choose to make Git no touch EOL the problem does not occur. So `.gitconfig` should have this:

```
[core]
        autocrlf = false
```
Then the only problems are `env` and `tar` in `package-build`. My tar fix works with the MingGW version of tar, but not the cygwin one. I guess we should find a more general solution for that.

**Comment by jaccarmac** [comment]
Hmmm, I believe I tried the `core.autocrlf` fix, but maybe I got messed up by the fact that Git uses different `.gitconfig` files for native and Cygwin, even if you run the same EXE. I'll give native Emacs a try with the MinGW tools from Windows Git.

**Comment by jaccarmac** [comment]
Waow. I somehow messed up setting `autocrlf`. Everything appears to be in order for the moment, outside the hack that is attaching `env` to the system path.

**Comment by jaccarmac** [comment]
Were you planning on submitting the `package-build` patch to milkypostman/melpa or should I?

**Comment by steckerhalter** [comment]
Well, I think it's more like a hack currently. We should make `env` unnecessary for Windows and find a better way to solve the tar issue. I will try to make a PR.

**Comment by steckerhalter** [comment]
So I think I found out if `tar` from here is used: http://gnuwin32.sourceforge.net/packages/gtar.htm

(you also need the dependencies in the zip)

Then it works without any modification. Can you verify that?

**Comment by jaccarmac** [comment]
Not sure what you mean by "without any modification". Without the updated `create-tar`, it still fails for me. With the updated function it works with both Git and Gnu versions of `tar`.

**Comment by steckerhalter** [comment]
ok, that's why I asked you to verify it because I couldn't believe it somehow :)

I probably had some code still active with the modified `create-tar`, thanks
