### ISSUE TITLE
error: pathspec 'snippets' did not match any file(s) known to git.

### ISSUE THREAD

**Issue by vyp** [quelpa/quelpa#74]
```
HEAD is now at 197db9f Merge pull request #578 from aluaces/patch-1
Entering 'snippets'
error: pathspec 'snippets' did not match any file(s) known to git.
Did you forget to 'git add'?
Stopping at 'snippets'; script returned non-zero status.
```

Happens when doing `quelpa-upgrade`, whilst having this recipe for yasnippet:

```
(quelpa
 '(yasnippet
   :fetcher github
   :repo "capitaomorte/yasnippet"
   :files ("yasnippet.el" "snippets")))
```

from https://github.com/milkypostman/melpa/blob/master/recipes/yasnippet.

I'm not sure if this is a quelpa issue though, but I'm not sure how to debug/fix it. `~/.emacs.d/quelpa/build/yasnippet/snippets` exists and is being tracked by git.

**Comment by steckerhalter** [comment]
I tried installing yasnippet with the recipe above and used `quelpa-upgrade` but didn't get any error.

Is it actually trying to do an upgrade or just checking? The error seems to be coming from git (I couldn't find anything related to "entering" or "stopping" in either quelpa or package-build).

What does `quelpa-cache` contain (C-H v quelpa-cache RET) related to yasnippet?

**Comment by vyp** [comment]
`quelpa-cache` for yasnippet:

```
(yasnippet :fetcher github :repo "capitaomorte/yasnippet" :files
            ("yasnippet.el" "snippets"))
```

Yes, that's a git error, it usually happens the path/file is unstaged/untracked. I still don't know what exactly is going on here (because I'm new to emacs, unfamiliar with like everything), but I think it's just trying to check (for updates?). (Does quelpa check for updates, before updating?) Because I only installed yasnippet via quelpa (using that recipe) yesterday, and [yasnippet](https://github.com/capitaomorte/yasnippet) hasn't had a commit since then.

I will try to reproduce this again soon, or now.

**Comment by vyp** [comment]
Also note that the snippets directory in yasnippet is a submodule, which may or may not be relevant. My understanding is that it's an optional repository that holds many default snippets for yasnippet. Optional because you do not need to install it to install yasnippet. However, I think the melpa recipe has `"snippets"` because it is expected to be installed by default too. (Not sure.)

**Comment by steckerhalter** [comment]
Ok. If you can reproduce it, look at edebug http://www.gnu.org/software/emacs/manual/html_node/elisp/Edebug.html with which it might be possible to find out what is going on.

From what you are saying about the submodule it might be related to that:

```cl
(defun package-build--checkout-git (name config dir)
  "Check package NAME with config CONFIG out of git into DIR."
  (let ((repo (plist-get config :url))
        (commit (or (plist-get config :commit)
                    (let ((branch (plist-get config :branch)))
                      (when branch
                        (concat "origin/" branch))))))
    (with-current-buffer (get-buffer-create "*package-build-checkout*")
      (goto-char (point-max))
      (cond
       ((and (file-exists-p (expand-file-name ".git" dir))
             (string-equal (package-build--git-repo dir) repo))
        (package-build--princ-exists dir)
        (package-build--run-process dir "git" "remote" "update"))
       (t
        (when (file-exists-p dir)
          (delete-directory dir t))
        (package-build--princ-checkout repo dir)
        (package-build--run-process nil "git" "clone" repo dir)))
      (if package-build-stable
          (let* ((bound (goto-char (point-max)))
                 (tag-version (and (package-build--run-process dir "git" "tag")
                                   (or (package-build--find-tag-version-newest
                                        "^\\(?:v[.-]?\\)?\\([0-9]+[^ \t\n]*\\)$" bound)
                                       (error
                                        "No valid stable versions found for %s"
                                        name)))))
            ;; Using reset --hard here to comply with what's used for
            ;; unstable, but maybe this should be a checkout?
            (package-build--run-process dir "git" "reset" "--hard" (concat "tags/" (car tag-version)))
            (package-build--run-process dir "git" "submodule" "update" "--init" "--recursive")
            (cadr tag-version))
        (package-build--run-process dir "git" "reset" "--hard"
                        (or commit (concat "origin/" (package-build--git-head-branch dir))))
        (package-build--run-process dir "git" "submodule" "update" "--init" "--recursive")
        (apply 'package-build--run-process dir "git" "log" "--first-parent" "-n1" "--pretty=format:'\%ci'"
               (package-build--expand-source-file-list dir config))
        (package-build--find-parse-time
         "\\([0-9]\\{4\\}-[0-9]\\{2\\}-[0-9]\\{2\\} [0-9]\\{2\\}:[0-9]\\{2\\}:[0-9]\\{2\\}\\( [+-][0-9]\\{4\\}\\)?\\)")))))
```

you see that `package-build` it tries to run `git submodule update --init --recursive`

what happens if you do this in a shell?

**Comment by vyp** [comment]
> what happens if you do this in a shell?

Nothing, essentially (exits with 0 status). That makes sense I think because the submodule has already been checked out the first time I installed it.

The error still happens with `quelpa-upgrade` for me. If you can't reproduce it, this is probably then neither an issue with quelpa nor yasnippet, meaning it would have to be some strange artifact of my system. I am using git 2.4.5 and emacs 24.5.1 (latest master branch quelpa), what about you?

**Comment by vyp** [comment]
You know when you run `quelpa-upgrade` and it fetches origin for updates (at least for git sources)? That is when it happens... (Does quelpa fetch origin itself, or something else? I don't see quelpa trying to fetch anywhere in the source code.)

Also, this is a side thing, but I'm a bit lost on how to start using edebug for say `quelpa-upgrade`? Say I `eval-defun` it, then calling `M-x quelpa-upgrade` does not seem to active edebug, so now what? (I have used gdb before, so I understand the concept of edebug at least.)

**Comment by steckerhalter** [comment]
these things happen in `package-build` which is the library that MELPA uses to build their packages which they serve in their package-archive. quelpa uses the same library to build the packages locally.

On this system I'm using emacs 24.4.1 and git 2.1.4

try M-x find-function package-build--checkout-git RET

It think that's the function where the problem occurs. So you would run `M-x edebug-defun` there and after that when you run `quelpa-upgrade` it should start the debugger.  Maybe you can step through with SPC and see where the error occurs.

Does the error also happen with:

```cl
(quelpa
 '(yasnippet
   :fetcher github
   :repo "capitaomorte/yasnippet"
   :files ("yasnippet.el" "snippets")) :upgrade t)
```

If yes then that would make it easier to debug since it doesn't go through all other packages.

**Comment by vyp** [comment]
> Does the error also happen with: [...]

This actually gives more information about it (at emacs startup) which doesn't come up with `quelpa-upgrade`:

```
Fetcher: github
Source: capitaomorte/yasnippet

Updating /home/rws/.emacs.d/quelpa/build/yasnippet/
Quelpa: failed to checkout `yasnippet': `Command '(env LC_ALL=C /usr/bin/timeout -k 60 600 git submodule foreach --recursive git submodule deinit $path)' exited with non-zero status 1: Fetching origin
HEAD is now at 197db9f Merge pull request #578 from aluaces/patch-1
Entering 'snippets'
error: pathspec 'snippets' did not match any file(s) known to git.
Did you forget to 'git add'?
Stopping at 'snippets'; script returned non-zero status.
```

so the line that seems to fail is https://github.com/milkypostman/melpa/blob/6425fa7c188f7fe6bb102de7ef5a803a89b8f5c3/package-build.el#L544

So this might actually be a package-build bug (the line looks like it was introduced just a couple of days ago too!), I'm going to open an issue there. Thanks very much for your help.

**Comment by steckerhalter** [comment]
ok, so didn't have the latest `package-build` on my system then. I get the same error after updating it.

**Comment by vyp** [comment]
For anyone that cares, a workaround that should work for yasnippet at least, is to remove `"snippets"` from the above recipe and follow https://github.com/AndreaCrotti/yasnippet-snippets/tree/master#how-to-install. Besides the snippets submodule in yasnippet is quite outdated right now.

That doesn't solve what seems to be a bug in package-build though.
