### ISSUE TITLE
Trigger travis build to detect errors due to changes in package-build.el

### ISSUE THREAD

**Issue by steckerhalter** [quelpa/quelpa#75]
`package-build.el` is being changed quite often and currently we have no automated way to detect braking changes (like the namespace change a few weeks ago).

Probably something here could be useful: http://stackoverflow.com/questions/17606874/trigger-a-travis-ci-rebuild-without-pushing-a-commit

Ideally it would send us an email if the build fails...

**Comment by steckerhalter** [comment]
I've setup a cronjob with https://github.com/travis-ci/travis.rb that runs once every night and triggers a rebuild of the latest job on master:

```bash
travis restart $(travis show master -r quelpa/quelpa | grep Job | sed 's/.*#\([0-9]*\)\..*/\1/') -r quelpa/quelpa -t <access token>
```

travis never sent me email for failed builds so that's something to look into. @wasamasa do you get emails for failed quelpa builds?

**Comment by steckerhalter** [comment]
Ok, that's weird. it says it ran the build again: https://travis-ci.org/quelpa/quelpa
But in the log it uses an old package-build version:

```
Wrote /tmp/quelpa50425LA/package-build-20150603.1934.el
Wrote /home/travis/.emacs.d/elpa/package-build-20150603.1934/package-build.el
Wrote /home/travis/.emacs.d/elpa/package-build-20150603.1934/package-build-pkg.el
Wrote /home/travis/.emacs.d/elpa/package-build-20150603.1934/package-build-autoloads.el
```

I'll check tomorrow when the cron has run

**Comment by steckerhalter** [comment]
So Travis was showing me the old log (because I'm using Policeman to block all kinds of external scripts):

```bash
Wrote /tmp/quelpa5042vEj/package-build-20150711.1529.el
Wrote /home/travis/.emacs.d/elpa/package-build-20150711.1529/package-build.el
Wrote /home/travis/.emacs.d/elpa/package-build-20150711.1529/package-build-pkg.el
Wrote /home/travis/.emacs.d/elpa/package-build-20150711.1529/package-build-autoloads.el
```

so then there is just the question if emails are going to be sent or not if it fails

**Comment by wasamasa** [comment]
No, I'm not getting any mail notifications either.

**Comment by steckerhalter** [comment]
I think it was because I hadn't verified the email for the build account. I did that now. Automated build worked this night so we will see what happens if it fails later (hopefully).

**Comment by wasamasa** [comment]
Still no notification. I've seen that you added some related commits, did you gather new insights meanwhile?

**Comment by steckerhalter** [comment]
Yeah, I have received an email for the latest build. If you want you can add your email in .travis.yml as well (see http://docs.travis-ci.com/user/notifications/ for config, maybe it needs some tweaking)

**Comment by wasamasa** [comment]
I'd like receiving mail notifications for build failures only which is possible to customize, but apparently only for all mail addresses listed. Would you be ok with that?

The other thing I've noticed is that Travis supports IRC notification. Assuming we'd both hang out on `#emacs-quelpa` (or something else like that), it would be useful to get at least these notifications and maybe more, like for any build in progress or even new pull requests/issues.

**Comment by steckerhalter** [comment]
> I'd like receiving mail notifications for build failures only which is possible to customize, but apparently only for all mail addresses listed. Would you be ok with that?

Yeah, sure.

> The other thing I've noticed is that Travis supports IRC notification. Assuming we'd both hang out on #emacs-quelpa (or something else like that), it would be useful to get at least these notifications and maybe more, like for any build in progress or even new pull requests/issues.

I'm not using IRC anymore, but feel free to add whatever notifications you'd like to have.
