### ISSUE TITLE
Pruning stale branches

### ISSUE THREAD

**Issue by wasamasa** [quelpa/quelpa#78]
I've removed two of my own branches as one had no more of a purpose and the other was merely for testing purposes. https://github.com/quelpa/quelpa/branches lists a few more stale branches, are they good to go as well?

**Comment by steckerhalter** [comment]
I don't think we need any of them...

**Comment by wasamasa** [comment]
Not even the Github Pages one?

**Comment by steckerhalter** [comment]
don't think so... just deleted them all
