### ISSUE TITLE
Using quelpa more

### ISSUE THREAD

**Issue by priyadarshan** [quelpa/quelpa#79]
I have been using `quelpa` for quite some time, and I am so happy such a well thought out package tool exists in the Emacs ecosystem.

I was wondering if it is possible to have `quelpa` transparently take over some `package.el` functionalities?

I would be especially interested in:

- having @jwiegley's `(use-package somepackage :ensure t)` use `(quelpa 'somepackage)`, instead of default package system.
- when using built-in Emacs package management system, being able to install `somepackage` via `quelpa`. The same if using other package interface, like @Malabarba's [https://github.com/Malabarba/paradox](paradox).

Thank you for `quelpa`!

**Comment by wasamasa** [comment]
Regarding the former, https://github.com/jaccarmac/quse-package

I'm not sure of the benefits of the latter. `M-x list-packages` list pre-built packages available from existing archives. Quelpa builds packages from scratch (and uses MELPA's recipes by default). Would you envision something like an extra keybinding that looks up the name of the package at point, checks whether it's in MELPA, fetches the recipe, then builds an even newer snapshot than that and installs it?

If yes, that could be either a separate package or addition to the paradox package. Quelpa is supposed to be a simple build tool, nothing more than that.

**Comment by vyp** [comment]
@wasamasa But use-package still works with quelpa right? (Disregarding `:ensure`.)

**Comment by vyp** [comment]
Answered my own question, sorry I missed https://github.com/jaccarmac/quse-package/blob/master/quse-package.org.

**Comment by priyadarshan** [comment]
Thank you, `quse-package` is exactly was I was looking for.

Regarding the rest, personally I would prefer to have all my packages managed via `quelpa`, not going through built-in Emacs package system at all.

While keeping `quelpa` as simple as possible, would it still be possible perhpas to defavice some `package` functions, so that a few actions one chooses via the built-in system (install, delete, update), the appropriate `quelpa` function would be called instead?

If so, could you give me a hint, so I could perhaps implement it in my own init file?

**Comment by Malabarba** [comment]
@wasamasa 
> M-x list-packages list pre-built packages available from existing archives

What do you mean? The archives only offer package sources, and compilation happens at the user's computer.

> Would you envision something like an extra keybinding that looks up the name of the package at point, checks whether it's in MELPA, fetches the recipe, then builds an even newer snapshot than that and installs it?

Btw, I'd be happy to take PRs on Paradox for that

**Comment by wasamasa** [comment]
@priyadarshan Quelpa only offers a function for building and installing a package. While you can install/update by just calling the Quelpa form again (like, by putting it in your init file or using `M-x quelpa`) or upgrade all packages with `M-x quelpa-upgrade` (which runs the Quelpa function on all cached installation invocations), there is no intention of going beyond that, so you'll need to use `M-x list-packages` to do other options like looking for packages or deleting them. Perhaps look at https://github.com/cask/epl to write your own commands as this abstracts away over package.el's "most striking idiocies".

@Malabarba Building a package ≠ compiling it. I'm specifically speaking of the task package-build.el solves, namely fetching files and turning them (after light preprocessing) into appropriately named tarballs or single files that are offered on the package archive.

**Comment by Malabarba** [comment]
> Building a package ≠ compiling it.

Yes, sorry. I read that too quickly. :)

**Comment by vsrepo** [comment]
Thank you for clarifying that. I shall work on it.

**Comment by steckerhalter** [comment]
I was just having a look at the `use-package` docs. It can be extended with custom handlers and it shouldn't be too hard to add a handler similar to `:ensure` for quelpa: https://github.com/jwiegley/use-package/blob/master/use-package.el#L421

**Comment by steckerhalter** [comment]
here's a first shot at it:

```cl
(quelpa '(use-package :fetcher github :repo "jwiegley/use-package" :files ("use-package.el")))
(require 'use-package)
(push :quelpa use-package-keywords)

(defun use-package-normalize/:quelpa (name-symbol keyword args)
  (let ((arg (car args)))
    (pcase arg
      ((or `nil `t) (list name-symbol))
      ((pred symbolp) args)
      ((pred listp) (cond
                     ((listp (car arg)) arg)
                     ((string-match "^:" (symbol-name (car arg))) (cons name-symbol arg))
                     ((symbolp (car arg)) arg)
                     ((t nil))))
      (_ nil))))

(defun use-package-handler/:quelpa (name-symbol keyword args rest state)
  (let ((body (use-package-process-keywords name-symbol rest state)))
    ;; This happens at macro expansion time, not when the expanded code is
    ;; compiled or evaluated.
    (when args
      (unless (require 'quelpa nil t)
        (with-temp-buffer
          (url-insert-file-contents "https://raw.github.com/quelpa/quelpa/master/bootstrap.el")
          (eval-buffer)))
      (apply 'quelpa args))
    body))

;; with that it's possible to call `use-package' with all kinds of arguments
(use-package abc-mode :quelpa) ;installs abc-mode with quelpa
(use-package abc-mode :quelpa t) ;does the same
(use-package abc-mode :quelpa abc-mode) ;again... (if the package would have another name)
(use-package abc-mode :quelpa (:upgrade t)) ;passes upgrade parameter to quelpa
(use-package abc-mode :quelpa (abc-mode :fetcher github :repo "mkjunker/abc-mode")) ;uses recipe
(use-package abc-mode :quelpa ((abc-mode :fetcher github :repo "mkjunker/abc-mode") :upgrade t)) ;recipe with plist arguments
```

possibly buggy... so beware! :)

**Comment by priyadarshan** [comment]
@steckerhalter Thank you, this is wonderful, I will try it for a few hours and let you know.

I rather prefer this approach than the macro approach, as I prefer to maintain the same synatx (`use-package` vs `quse-package`)

**Comment by priyadarshan** [comment]
@steckerhalter It works very well! Thank you so much.

**Comment by steckerhalter** [comment]
My pleasure... note that `(push :quelpa use-package-keywords)` isn't optimal since it puts the keyword first (even before :disabled). That should be fixed (or the custom edited manually).

**Comment by priyadarshan** [comment]
Among the `quelpa` users I think quite a few also use `use-package`. It would be great for them to be able to access this code somehow.

Perhaps as separate tiny repository, or even a gist?

A proper MELPA package would be of course ideal.

Thank you once again.

**Comment by steckerhalter** [comment]
I'll first check if it can be merged into `use-package` directly

**Comment by steckerhalter** [comment]
@priyadarshan made a repo here: https://github.com/quelpa/quelpa-use-package
I'd like to wait a bit with adding it to MELPA since it hasn't been tested much (and I'm not using `use-package` myself yet)

**Comment by priyadarshan** [comment]
Thank you so much for the repository, and for the code. Quite instructive!

**Comment by steckerhalter** [comment]
you're welcome. I just tweaked it a bit so that the `:quelpa` handler follows `:if` and `:requires` meaning that quelpa is not executed if the requirement is not fulfilled.

can we close this issue then?

**Comment by priyadarshan** [comment]
Yes, this issue can be closed on my part. Thanks again, to all the `quelpa` team.
