### ISSUE TITLE
Quelpa fail to update a package from local git

### ISSUE THREAD

**Issue by deepfire** [quelpa/quelpa#82]
The following fails to recompile the package, when it was changed -- in my case commit amended:
```
(quelpa (list 'haskell-mode :url "/path/to/my/local/git/repo" :fetcher 'git) :upgrade t)
```
This sort of kills the local interactive flow of development that I hoped Quelpa would facilitate..

**Comment by steckerhalter** [comment]
Try with url format?

```cl
(quelpa '(haskell-mode :url "file:///path/to/git/repo" :fetcher git) :upgrade t)
```

**Comment by deepfire** [comment]
Didn't make any observable difference..

**Comment by deepfire** [comment]
Seems like `quelpa-setup-p` returns NIL.

**Comment by wasamasa** [comment]
Hmm, it should work if you've managed checking out MELPA previously...

**Comment by steckerhalter** [comment]
```cl
(setq quelpa-update-melpa-p t)
```

otherwise it's trying to update the melpa repo via github

**Comment by deepfire** [comment]
@steckerhalter, I have tried `quelpa-update-melpa-p` to be both T and NIL.

Now I can't make quelpa update from local git at all, for some reason.. internet connection or not..

**Comment by deepfire** [comment]
`file:///` wasn't the good URL for git, after all, plain path works much better.

**Comment by deepfire** [comment]
Disregard my message about non-`file:///` URI working better -- still can't get updates from local git to work.

**Comment by deepfire** [comment]
To make it clear -- the following doesn't update the package, if I change HEAD in the git repo:
```
(quelpa '(haskell-mode :url "/home/deepfire/src/haskell-mode/" :fetcher git) :upgrade t)
```
It does "update" it, if I manually remove the package from `~/.emacs.d/elpa/`.

**Comment by steckerhalter** [comment]
Well, it only updates if the commit date is newer than the installed one (the version number is taken from the git commit date, this is what [package-build](https://github.com/milkypostman/melpa/blob/master/package-build.el) (the melpa build library) does

**Comment by deepfire** [comment]
Aha, so amending the commit is supposed to facilitate the update, I see..

**Comment by deepfire** [comment]
And indeed it does works as you say!

Closing the issue -- thanks a lot!

**Comment by vyp** [comment]
@deepfire FYI I forgot to tell you about https://github.com/quelpa/quelpa#file. It was basically inspired by this issue. (see #91 for details)
