### ISSUE TITLE
Quelpa is building certain packages incorrectly

### ISSUE THREAD

**Issue by Seeq** [quelpa/quelpa#98]
Installing emmet-mode seems to be causing problems when building the latest branch from [github](https://github.com/smihica/emmet-mode) using quelpa or having quelpa use the recipe from melpa. It's leaving a small file in `elpa/emmet-mode-*/emmet-mode.el` that is about 600 lines long. Quelpa also seems to be leaving the full sized (~4k lines) version inside of `quelpa/build/emmet-mode`

The package installs just fine if I have quelpa download the stable version, or by doing it the "usual way" and setting up package downloading the way that melpa site suggests.

I've tried bisecting my emacs config, and it still doesn't work even after going back to the times I remember it working.

Any idea on what could be causing this?

**Comment by vyp** [comment]
Is there an error of some sort?

**Comment by Seeq** [comment]
Using emmet gives me `emmet-transform: Symbol's function definition is void: emmet-html-transform`
which I'm assuming is from emmet-mode.el only having a fraction of the lines it's supposed to since this doesn't happen in the cases that emmet-mode.el is ~4k lines.

**Comment by vyp** [comment]
I can reproduce with `M-x quelpa` on emacs 24.5.2.

Here is my compile log for it:

```
Leaving directory `/home/u/.emacs.d/elpa/emmet-mode-20151006.1250'

Compiling file /home/u/.emacs.d/elpa/emmet-mode-20151006.1250/emmet-mode-pkg.el at Sun Dec 13 18:22:38 2015
Entering directory `/home/u/.emacs.d/elpa/emmet-mode-20151006.1250/'

Compiling file /home/u/.emacs.d/elpa/emmet-mode-20151006.1250/emmet-mode.el at Sun Dec 13 18:22:38 2015

In end of data:
emmet-mode.el:643:1:Warning: the following functions are not known to be defined: emmet-css-transform,
    emmet-html-transform

Compiling no file at Sun Dec 13 18:25:23 2015
```

As you can see there's a warning which says the functions `emmet-css-transform` and `emmet-html-transform` are not defined.

At line 641 of that 4002 line https://github.com/smihica/emmet-mode/blob/master/emmet-mode.el file, you can see the comment `;;; emmet-mode ends here`. I'm guessing something (perhaps package.el) is seeing that and stopping at that point. Which means maybe this is an upstream error where the author should define any needed functions such as `emmet-css-tranform` and `emmet-html-transform` above line 641 somewhere.

However, you say the installation works fine when you simply install via the melpa repository, which I think it shouldn't. So I may be wrong...

**Comment by steckerhalter** [comment]
try this:

- download `emmet-mode.el`
- `M-x package-install-file RET` (Emacs function to install a package locally)
- then choose the `emmet-mode.el` file
- you will see:
```
emmet-mode.el:642:1:Warning: the following functions are not known to be defined:
    emmet-css-transform, emmet-html-transform
```

in the compile log. it's exactly as @vyp says. you can't have code below `;;; emmet-mode ends here` because that's how emacs is told that the file is finished

that it works with melpa is a coincidence (probably because it doesn't use `package-install-file`). in our case it's not quelpa that does not consider the code lines below the `ends here` line but Emacs itself via `package-install-file`

**Comment by Seeq** [comment]
Ah, got it. Thanksyou for the help, I'll take it up with emmet-mode's maintainer then.
