### ISSUE TITLE
quelpa participation

### ISSUE THREAD

**Issue by steckerhalter** [quelpa/quelpa#99]
@vyp hi I've sent you an email asking if you want to help maintaining quelpa. maybe you didn't get or see it? since you are always the first person to answer on issues it would make sense to me :)

**Comment by vyp** [comment]
Hmm I can't see it.. I've sent you an email so that you can get my email address, because I remember emailing you before. Let me know if you got it. And of course you can close this if you do.

**Comment by vyp** [comment]
Otherwise I'm still on irc (freenode) for a few more hours (from now). nick is "xd1le".

**Comment by vyp** [comment]
Thanks, I got the email now.
